// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 60000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		globalSetup: "./globalSetup.ts",
	},
});
