# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: embedding_backend_management
defmodule E2e.EmbeddingBackendManagementTest do
  use ExUnit.Case, async: false

  describe "embedding_backends_clear" do
    test "embedding_backends_clear" do
      result = Xberg.clear_embedding_backends()
    end
  end

  describe "embedding_backends_list" do
    test "embedding_backends_list" do
      result = Xberg.list_embedding_backends()
    end
  end
end
