# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5b65fe8ac640bf4cdf1e1a281c4b41b6d0d521d562ffcfc7007265ad142fb846
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: ocr_backend_management
defmodule E2e.OcrBackendManagementTest do
  use ExUnit.Case, async: false

  describe "ocr_backends_clear" do
    test "ocr_backends_clear" do
      result = Xberg.clear_ocr_backends()
    end
  end

  describe "ocr_backends_list" do
    test "ocr_backends_list" do
      result = Xberg.list_ocr_backends()
    end
  end

  describe "ocr_backends_unregister" do
    test "ocr_backends_unregister" do
      result = Xberg.unregister_ocr_backend("nonexistent-backend-xyz")
    end
  end
end
