# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: registry
defmodule E2e.RegistryTest do
  use ExUnit.Case, async: false

  describe "list_embedding_backends" do
    test "list_embedding_backends" do
      result = Xberg.list_embedding_backends()
    end
  end

  describe "list_ocr_backends" do
    test "list_ocr_backends" do
      result = Xberg.list_ocr_backends()
    end
  end

  describe "list_post_processors" do
    test "list_post_processors" do
      result = Xberg.list_post_processors()
    end
  end

  describe "list_renderers" do
    test "list_renderers" do
      result = Xberg.list_renderers()
    end
  end

  describe "list_validators" do
    test "list_validators" do
      result = Xberg.list_validators()
    end
  end
end
