# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: renderer_management
defmodule E2e.RendererManagementTest do
  use ExUnit.Case, async: false

  describe "renderers_clear" do
    test "renderers_clear" do
      result = Xberg.clear_renderers()
    end
  end

  describe "renderers_list" do
    test "renderers_list" do
      result = Xberg.list_renderers()
    end
  end
end
