# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: renderer_management
defmodule E2e.RendererManagementTest do
  use ExUnit.Case, async: false

  describe "renderers_clear" do
    test "renderers_clear" do
      result = Xberg.clear_renderers()
    end
  end

  describe "renderers_list" do
    test "renderers_list" do
      result = Xberg.list_renderers()
    end
  end
end
