# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: validator_management
defmodule E2e.ValidatorManagementTest do
  use ExUnit.Case, async: false

  describe "validators_clear" do
    test "validators_clear" do
      result = Xberg.clear_validators()
    end
  end

  describe "validators_list" do
    test "validators_list" do
      result = Xberg.list_validators()
    end
  end
end
