// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5b65fe8ac640bf4cdf1e1a281c4b41b6d0d521d562ffcfc7007265ad142fb846
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Xberg;
using static Xberg.XbergConverter;

namespace Xberg
{
    /// <summary>E2e tests for category: tokenizer_backend_management.</summary>
    public class TokenizerBackendManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_TokenizerBackendsClear()
        {
            // Clear all tokenizer backends and verify list is empty
            XbergConverter.ClearTokenizerBackends();
        }

        [Fact]
        public void Test_TokenizerBackendsList()
        {
            // List all registered tokenizer backends
            var result = XbergConverter.ListTokenizerBackends();

        }


    }
}
