// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package io.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.Xberg;
import io.xberg.ExtractionConfig;
import java.util.Optional;
import io.xberg.JsonUtil;
import org.junit.jupiter.api.BeforeAll;
/** E2e tests for category: tokenizer_backend_management. */
public class TokenizerBackendManagementTest {
    @BeforeAll
    static void initEnv() {        if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
            System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true");
        }    }

    @Test
    void testTokenizerBackendsClear() throws Exception {
        // Clear all tokenizer backends and verify list is empty
        Xberg.clearTokenizerBackends();


    }


    @Test
    void testTokenizerBackendsList() throws Exception {
        // List all registered tokenizer backends
        var result = Xberg.listTokenizerBackends();


    }

}
