// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: embedding_backend_management

use xberg::{clear_embedding_backends, list_embedding_backends};

#[test]
fn test_embedding_backends_clear() {
    // Clear all embedding backends and verify list is empty
    let _ = clear_embedding_backends();
}

#[test]
fn test_embedding_backends_list() {
    // List all registered embedding backends
    let _ = list_embedding_backends();
}
