// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5f99ce7aaf20a24b3f83e3c5a0acf8a680598460ed7e37475aac9da52248fdc4
// To regenerate: alef generate
// To verify freshness: alef verify
//! E2e tests for category: embedding_backend_management

use xberg::{clear_embedding_backends, list_embedding_backends};

#[test]
fn test_embedding_backends_clear() {
    // Clear all embedding backends and verify list is empty
    clear_embedding_backends().expect("call failed");
}

#[test]
fn test_embedding_backends_list() {
    // List all registered embedding backends
    let _ = list_embedding_backends().expect("call failed");
}
