// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8345994406c6c645f35e0901138c81fdff86d7f16965389f94c9286db6fa4084
// To regenerate: alef generate
// To verify freshness: alef verify
//! E2e tests for category: post_processor_management

use xberg::{clear_post_processors, list_post_processors};

#[test]
fn test_post_processors_clear() {
    // Clear all post-processors and verify list is empty
    clear_post_processors().expect("call failed");
}

#[test]
fn test_post_processors_list() {
    // List all registered post-processors
    let _ = list_post_processors().expect("call failed");
}
