// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: reranker_backend_management

use xberg::{clear_reranker_backends, list_reranker_backends};

#[test]
fn test_clear_reranker_backends() {
    // Clear all reranker backends and verify list is empty
    let _ = clear_reranker_backends();
}

#[test]
fn test_list_reranker_backends() {
    // List all registered reranker backends
    let _ = list_reranker_backends();
}
