// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5b65fe8ac640bf4cdf1e1a281c4b41b6d0d521d562ffcfc7007265ad142fb846
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: reranker_backend_management

use xberg::{clear_reranker_backends, list_reranker_backends};

#[test]
fn test_clear_reranker_backends() {
    // Clear all reranker backends and verify list is empty
    let _ = clear_reranker_backends();
}

#[test]
fn test_list_reranker_backends() {
    // List all registered reranker backends
    let _ = list_reranker_backends();
}
