// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a33f37f2d9ea2be40fb70d6811f7c6e68df6083da24f268e10332e11761e51a1
// To regenerate: alef generate
// To verify freshness: alef verify
//! E2e tests for category: tokenizer_backend_management

use xberg::{clear_tokenizer_backends, list_tokenizer_backends};

#[test]
fn test_tokenizer_backends_clear() {
    // Clear all tokenizer backends and verify list is empty
    clear_tokenizer_backends().expect("call failed");
}

#[test]
fn test_tokenizer_backends_list() {
    // List all registered tokenizer backends
    let _ = list_tokenizer_backends().expect("call failed");
}
