// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: tokenizer_backend_management

use xberg::{clear_tokenizer_backends, list_tokenizer_backends};

#[test]
fn test_tokenizer_backends_clear() {
    // Clear all tokenizer backends and verify list is empty
    let _ = clear_tokenizer_backends();
}

#[test]
fn test_tokenizer_backends_list() {
    // List all registered tokenizer backends
    let _ = list_tokenizer_backends();
}
