// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: validator_management

use xberg::{clear_validators, list_validators};

#[test]
fn test_validators_clear() {
    // Clear all validators and verify list is empty
    let _ = clear_validators();
}

#[test]
fn test_validators_list() {
    // List all registered validators
    let _ = list_validators();
}
