// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d1702589cf178f46cc6e25ec22e0ff71359bcd8ece40679cfac0cc5f27613b6e
// To regenerate: alef generate
// To verify freshness: alef verify
//! E2e tests for category: validator_management

use xberg::{clear_validators, list_validators};

#[test]
fn test_validators_clear() {
    // Clear all validators and verify list is empty
    clear_validators().expect("call failed");
}

#[test]
fn test_validators_list() {
    // List all registered validators
    let _ = list_validators().expect("call failed");
}
