# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ArchiveEntry do
  @moduledoc """
  A single file extracted from an archive.

  When archives (ZIP, TAR, 7Z, GZIP) are extracted with recursive extraction
  enabled, each processable file produces its own full `ExtractedDocument`.
  """

  @typedoc "A single file extracted from an archive."
  @type t :: %__MODULE__{
          path: String.t() | nil,
          mime_type: String.t() | nil,
          result: Xberg.ExtractedDocument.t()
        }

  defstruct path: nil,
            mime_type: nil,
            result: nil
end
