# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.BrowserBackend do
  @moduledoc "Browser backend used for JavaScript rendering."

  @typedoc "Browser backend used for JavaScript rendering."
  @type t :: :chromiumoxide | :native

  @chromiumoxide :chromiumoxide
  @native :native

  @doc "Existing Chromium/CDP backend powered by chromiumoxide."
  @spec chromiumoxide() :: t()
  def chromiumoxide, do: @chromiumoxide
  @doc "Crawlberg-owned native browser backend derived from Obscura."
  @spec native() :: t()
  def native, do: @native
end
