# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.BrowserBackend do
  @moduledoc "Browser backend used for JavaScript rendering."

  @typedoc "Browser backend used for JavaScript rendering."
  @type t :: :chromiumoxide | :native

  @chromiumoxide :chromiumoxide
  @native :native

  @doc "Existing Chromium/CDP backend powered by chromiumoxide."
  @spec chromiumoxide() :: t()
  def chromiumoxide, do: @chromiumoxide
  @doc "Crawlberg-owned native browser backend derived from Obscura."
  @spec native() :: t()
  def native, do: @native
end
