# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.CallMode do
  @moduledoc """
  How a structured-extraction preset is dispatched to the model.

  This is the preset-facing call mode (the `preferred_call_mode` field of a
  `Preset`). The structured pipeline has a richer
  runtime-only decision enum with skip and fallback states; this 3-variant
  type is the stable, serializable surface presets and bindings depend on.
  """

  @typedoc "How a structured-extraction preset is dispatched to the model."
  @type t :: :text_only | :vision_only | :text_plus_vision

  @text_only :text_only
  @vision_only :vision_only
  @text_plus_vision :text_plus_vision

  @doc "Use the extracted text only."
  @spec text_only() :: t()
  def text_only, do: @text_only
  @doc "Use rasterized page images only."
  @spec vision_only() :: t()
  def vision_only, do: @vision_only
  @doc "Provide both extracted text and page images to the model."
  @spec text_plus_vision() :: t()
  def text_plus_vision, do: @text_plus_vision
end
