# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.CaptioningConfig do
  @moduledoc "Configuration for the VLM captioning post-processor."

  @typedoc "Configuration for the VLM captioning post-processor."
  @type t :: %__MODULE__{
  llm: Xberg.LlmConfig.t(),
  prompt: String.t() | nil,
  min_image_area: non_neg_integer()
  }

  defstruct llm: nil,
  prompt: nil,
  min_image_area: 0
end
