# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.CaptioningConfig do
  @moduledoc "Configuration for the VLM captioning post-processor."

  @typedoc "Configuration for the VLM captioning post-processor."
  @type t :: %__MODULE__{
          llm: Xberg.LlmConfig.t(),
          prompt: String.t() | nil,
          min_image_area: non_neg_integer()
        }

  defstruct llm: nil,
            prompt: nil,
            min_image_area: 0
end
