# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.CellChange do
  @moduledoc """
  A single changed cell within a table.

  Defined here (rather than only in `crate::diff`) so `RevisionDelta` can
  reference it unconditionally, without requiring the `diff` Cargo feature.
  `crate::diff` re-exports this type verbatim.
  """

  @typedoc "A single changed cell within a table."
  @type t :: %__MODULE__{
          row: non_neg_integer(),
          col: non_neg_integer(),
          from: String.t() | nil,
          to: String.t() | nil
        }

  defstruct row: 0,
            col: 0,
            from: nil,
            to: nil
end
