# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ChunkClassificationEnrichmentConfig do
  @moduledoc """
  Chunk-classification enrichment knob: how to multi-label individual chunks.

  Operates on `ExtractedDocument::chunks` in place — the caller must have
  already produced chunks (e.g. via `ExtractionConfig::chunking`) for this
  stage to have any effect; a document with no chunks is a no-op.
  """

  @typedoc "Chunk-classification enrichment knob: how to multi-label individual chunks."
  @type t :: %__MODULE__{
          config: Xberg.ChunkClassificationConfig.t()
        }

  defstruct config: nil
end
