# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ChunkInfo do
  @moduledoc "Information about a single chunk."

  @typedoc "Information about a single chunk."
  @type t :: %__MODULE__{
  index: non_neg_integer(),
  pages: Xberg.PageRange.t(),
  estimated_time_ms: non_neg_integer()
  }

  defstruct index: 0,
  pages: nil,
  estimated_time_ms: 0
end
