# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ChunkingConfig do
  @moduledoc """
  Chunking configuration.

  Configures text chunking for document content, including chunk size,
  overlap, trimming behavior, and optional embeddings.

  Use `..Default::default()` when constructing to allow for future field additions:
  ```rust
  let config = ChunkingConfig {
      max_characters: 500,
      ..Default::default()
  };
  ```
  """

  @typedoc "Chunking configuration."
  @type t :: %__MODULE__{
          max_characters: non_neg_integer(),
          overlap: non_neg_integer(),
          trim: boolean(),
          chunker_type: String.t() | nil,
          embedding: Xberg.EmbeddingConfig.t() | nil,
          sparse_embedding: Xberg.SparseEmbeddingConfig.t() | nil,
          late_interaction: Xberg.LateInteractionConfig.t() | nil,
          preset: String.t() | nil,
          sizing: String.t() | nil,
          prepend_heading_context: boolean(),
          topic_threshold: float() | nil,
          table_chunking: String.t() | nil,
          breadcrumb_target: String.t() | nil
        }

  defstruct max_characters: 1_000,
            overlap: 200,
            trim: true,
            chunker_type: :text,
            embedding: nil,
            sparse_embedding: nil,
            late_interaction: nil,
            preset: nil,
            sizing: :characters,
            prepend_heading_context: false,
            topic_threshold: nil,
            table_chunking: :split,
            breadcrumb_target: :content

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
