# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ChunkClassificationEnrichmentConfig do
  @moduledoc """
  Chunk-classification enrichment knob: how to multi-label individual chunks.

  Operates on `ExtractedDocument::chunks` in place — the caller must have
  already produced chunks (e.g. via `ExtractionConfig::chunking`) for this
  stage to have any effect; a document with no chunks is a no-op.
  """

  @typedoc "Chunk-classification enrichment knob: how to multi-label individual chunks."
  @type t :: %__MODULE__{
  config: Xberg.ChunkClassificationConfig.t()
  }

  defstruct config: nil
end
