# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.CodeContentMode do
  @moduledoc """
  Content rendering mode for code extraction.

  Controls how extracted code content is represented in the `content` field
  of `ExtractedDocument`.
  """

  @typedoc "Content rendering mode for code extraction."
  @type t :: :chunks | :raw | :structure

  @chunks :chunks
  @raw :raw
  @structure :structure

  @doc "Use TSLP semantic chunks as content (default)."
  @spec chunks() :: t()
  def chunks, do: @chunks
  @doc "Use raw source code as content."
  @spec raw() :: t()
  def raw, do: @raw
  @doc "Emit function/class headings + docstrings (no code bodies)."
  @spec structure() :: t()
  def structure, do: @structure
end
