# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.CodeBlockStyle do
  @moduledoc """
  Code block fence style in Markdown output.

  Determines how code blocks (`<pre><code>`) are rendered in Markdown.
  """

  @typedoc "Code block fence style in Markdown output."
  @type t :: :indented | :backticks | :tildes

  @indented :indented
  @backticks :backticks
  @tildes :tildes

  @doc "Indented code blocks (4 spaces). `CommonMark` standard."
  @spec indented() :: t()
  def indented, do: @indented
  @doc "Fenced code blocks with triple backticks. Default (GFM). Supports language hints."
  @spec backticks() :: t()
  def backticks, do: @backticks
  @doc "Fenced code blocks with tildes (~~~). Supports language hints."
  @spec tildes() :: t()
  def tildes, do: @tildes
end
