# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.CodeChunkInfo do
  @moduledoc """
  A single structurally-meaningful code chunk produced by tree-sitter parsing.

  Purpose-built payload owned by xberg — deliberately does not expose the upstream
  `tree_sitter_language_pack` types, so binding generators never need to resolve an
  external crate's types across FFI/language boundaries.
  """

  @typedoc "A single structurally-meaningful code chunk produced by tree-sitter parsing."
  @type t :: %__MODULE__{
  text: String.t() | nil,
  context_path: [String.t()],
  node_types: [String.t()],
  byte_start: non_neg_integer(),
  byte_end: non_neg_integer()
  }

  defstruct text: nil,
  context_path: [],
  node_types: [],
  byte_start: 0,
  byte_end: 0
end
