# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.CsvMetadata do
  @moduledoc "CSV/TSV file metadata."

  @typedoc "CSV/TSV file metadata."
  @type t :: %__MODULE__{
          row_count: non_neg_integer(),
          column_count: non_neg_integer(),
          delimiter: String.t() | nil,
          has_header: boolean(),
          column_types: [String.t()] | nil
        }

  defstruct row_count: 0,
            column_count: 0,
            delimiter: nil,
            has_header: false,
            column_types: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
