# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DiffLine do
  @moduledoc """
  A single line in a unified-diff hunk.

  Defined here (rather than only in `crate::diff`) so `RevisionDelta` can
  reference it unconditionally, without requiring the `diff` Cargo feature.
  `crate::diff` re-exports this type verbatim.
  """

  @typedoc "A single line in a unified-diff hunk."
  @type t :: term()

  @typedoc "Unchanged context line."
  @type context :: %{type: :context, value: String.t()}
  @typedoc "Line added in the \"after\" version."
  @type added :: %{type: :added, value: String.t()}
  @typedoc "Line removed from the \"before\" version."
  @type removed :: %{type: :removed, value: String.t()}
end
