# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DiffHunk do
  @moduledoc "A single contiguous hunk in a unified diff."

  @typedoc "A single contiguous hunk in a unified diff."
  @type t :: %__MODULE__{
  from_line: non_neg_integer(),
  from_count: non_neg_integer(),
  to_line: non_neg_integer(),
  to_count: non_neg_integer(),
  lines: [String.t() | nil]
  }

  defstruct from_line: 0,
  from_count: 0,
  to_line: 0,
  to_count: 0,
  lines: []
end
