# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DiffOptions do
  @moduledoc "Options controlling how two `ExtractedDocument` values are compared."

  @typedoc "Options controlling how two `ExtractedDocument` values are compared."
  @type t :: %__MODULE__{
  include_metadata: boolean(),
  include_embedded: boolean(),
  max_content_chars: non_neg_integer() | nil
  }

  defstruct include_metadata: true,
  include_embedded: true,
  max_content_chars: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
