# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DocumentNode do
  @moduledoc """
  A single node in the document tree.

  Each node has deterministic `id`, typed `content`, optional `parent`/`children`
  for tree structure, and metadata like page number, bounding box, and content layer.
  """

  @typedoc "A single node in the document tree."
  @type t :: %__MODULE__{
  id: String.t() | nil,
  content: String.t() | nil,
  parent: non_neg_integer() | nil,
  children: [non_neg_integer()],
  content_layer: String.t() | nil,
  page: non_neg_integer() | nil,
  page_end: non_neg_integer() | nil,
  bbox: Xberg.BoundingBox.t() | nil,
  annotations: [Xberg.TextAnnotation.t()],
  attributes: map() | nil
  }

  defstruct id: nil,
  content: :title,
  parent: nil,
  children: [],
  content_layer: :body,
  page: nil,
  page_end: nil,
  bbox: nil,
  annotations: [],
  attributes: nil
end
