# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DocumentMetadata do
  @moduledoc "Metadata about a document for analysis."

  @typedoc "Metadata about a document for analysis."
  @type t :: %__MODULE__{
          mime_type: String.t() | nil,
          size_bytes: non_neg_integer(),
          page_count: non_neg_integer() | nil,
          force_ocr: boolean(),
          user_chunk_config: Xberg.UserChunkConfig.t() | nil,
          chunking_enabled: boolean()
        }

  defstruct mime_type: nil,
            size_bytes: 0,
            page_count: nil,
            force_ocr: false,
            user_chunk_config: nil,
            chunking_enabled: false
end
