# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DocumentSummary do
  @moduledoc "Summary of an extracted document."

  @typedoc "Summary of an extracted document."
  @type t :: %__MODULE__{
  text: String.t() | nil,
  strategy: String.t() | nil,
  token_count: non_neg_integer() | nil
  }

  defstruct text: nil,
  strategy: :extractive,
  token_count: nil
end
