# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ElementMetadata do
  @moduledoc "Metadata for a semantic element."

  @typedoc "Metadata for a semantic element."
  @type t :: %__MODULE__{
  page_number: non_neg_integer() | nil,
  filename: String.t() | nil,
  coordinates: Xberg.BoundingBox.t() | nil,
  element_index: non_neg_integer() | nil,
  additional: map()
  }

  defstruct page_number: nil,
  filename: nil,
  coordinates: nil,
  element_index: nil,
  additional: %{}
end
