# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.EmailConfig do
  @moduledoc "Configuration for email extraction."

  @typedoc "Configuration for email extraction."
  @type t :: %__MODULE__{
  msg_fallback_codepage: non_neg_integer() | nil
  }

  defstruct msg_fallback_codepage: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
