# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.EmailAttachment do
  @moduledoc """
  Email attachment representation.

  Contains metadata and optionally the content of an email attachment.
  """

  @typedoc "Email attachment representation."
  @type t :: %__MODULE__{
  name: String.t() | nil,
  filename: String.t() | nil,
  mime_type: String.t() | nil,
  size: non_neg_integer() | nil,
  is_image: boolean(),
  data: binary() | nil
  }

  defstruct name: nil,
  filename: nil,
  mime_type: nil,
  size: nil,
  is_image: false,
  data: nil
end
