# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.EmbeddedChanges do
  @moduledoc "Changes to embedded archive children between two results."

  @typedoc "Changes to embedded archive children between two results."
  @type t :: %__MODULE__{
  added: [Xberg.ArchiveEntry.t()],
  removed: [Xberg.ArchiveEntry.t()],
  changed: [Xberg.EmbeddedDiff.t()]
  }

  defstruct added: [],
  removed: [],
  changed: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
