# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  @typedoc "Embedded file descriptor extracted from the PDF name tree."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          data: binary(),
          compressed_size: non_neg_integer(),
          mime_type: String.t() | nil
        }

  defstruct name: nil,
            data: <<>>,
            compressed_size: 0,
            mime_type: nil
end
