# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.EmbeddingsEmbeddingBackend do
  @moduledoc """
  Inference backend that an [`EmbeddingPreset`] runs on.

  `Onnx` presets require the `embeddings` feature (ONNX Runtime, not available on
  WASM/Android x86_64 emulator). `Static` presets require `static-embeddings`
  (pure-Rust model2vec inference, no ORT — the only dense-embedding backend
  available on `no-ort-target`).

  Defaults to `Onnx` via `#[serde(default)]` so every existing preset payload
  (which predates this field) keeps deserializing without change.
  """

  @typedoc "Inference backend that an [`EmbeddingPreset`] runs on."
  @type t :: :onnx | :static

  @onnx :onnx
  @static :static

  @doc "ONNX Runtime transformer inference (the historical, default backend)."
  @spec onnx() :: t()
  def onnx, do: @onnx
  @doc "Pure-Rust static (model2vec) inference — no ONNX Runtime."
  @spec static() :: t()
  def static, do: @static
end
