# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.EmbeddedDiff do
  @moduledoc "Diff for a single embedded archive entry that appears in both results."

  @typedoc "Diff for a single embedded archive entry that appears in both results."
  @type t :: %__MODULE__{
  path: String.t() | nil,
  diff: Xberg.ExtractionDiff.t()
  }

  defstruct path: nil,
  diff: nil
end
