# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.EmbeddedChanges do
  @moduledoc "Changes to embedded archive children between two results."

  @typedoc "Changes to embedded archive children between two results."
  @type t :: %__MODULE__{
          added: [Xberg.ArchiveEntry.t()],
          removed: [Xberg.ArchiveEntry.t()],
          changed: [Xberg.EmbeddedDiff.t()]
        }

  defstruct added: [],
            removed: [],
            changed: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
