# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExtractionConfidence do
  @moduledoc """
  Combined confidence on `[0, 1]`.

  When OCR did not run, the `ocr_aggregate` weight folds into `text_coverage`
  so the weighted sum still totals 1.0.
  """

  @typedoc "Combined confidence on `[0, 1]`."
  @type t :: %__MODULE__{
  text_coverage: float(),
  ocr_aggregate: float() | nil,
  schema_compliance: String.t() | nil,
  combined: float()
  }

  defstruct text_coverage: 0.0,
  ocr_aggregate: nil,
  schema_compliance: :all_valid,
  combined: 0.0
end
