# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExtractInputKind do
  @moduledoc "Source kind for [`ExtractInput`]."

  @typedoc "Source kind for [`ExtractInput`]."
  @type t :: :bytes | :uri

  @bytes :bytes
  @uri :uri

  @doc "Raw in-memory bytes."
  @spec bytes() :: t()
  def bytes, do: @bytes
  @doc "A filesystem path, `file://` URI, or HTTP(S) URL."
  @spec uri() :: t()
  def uri, do: @uri
end
