# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.FootnoteDefinition do
  @moduledoc """
  A footnote definition from markdown text.

  Represents `[^label]: content` declarations (including multi-line continuations).
  """

  @typedoc "A footnote definition from markdown text."
  @type t :: %__MODULE__{
  label: String.t() | nil,
  content: String.t() | nil,
  offset: non_neg_integer()
  }

  defstruct label: nil,
  content: nil,
  offset: 0
end
