# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Footnote do
  @moduledoc "Footnote in Djot."

  @typedoc "Footnote in Djot."
  @type t :: %__MODULE__{
  label: String.t() | nil,
  content: [Xberg.FormattedBlock.t()]
  }

  defstruct label: nil,
  content: []
end
