# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.FootnoteDefinition do
  @moduledoc """
  A footnote definition from markdown text.

  Represents `[^label]: content` declarations (including multi-line continuations).
  """

  @typedoc "A footnote definition from markdown text."
  @type t :: %__MODULE__{
  label: String.t() | nil,
  content: String.t() | nil,
  offset: non_neg_integer()
  }

  defstruct label: nil,
  content: nil,
  offset: 0
end
