# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.FormulaModel do
  @moduledoc "Formula recognition model selection."

  @typedoc "Formula recognition model selection."
  @type t :: :latex_ocr

  @latex_ocr :latex_ocr

  @doc "RapidLaTeXOCR (MIT, pix2tex-derived): resizer + encoder + decoder ONNX, ~180 MB total, downloaded on demand."
  @spec latex_ocr() :: t()
  def latex_ocr, do: @latex_ocr
end
