# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.Formula do
  @moduledoc """
  A mathematical formula extracted from a document.

  Three kinds of sources populate this type. Layout-guided OCR detects
  formula regions and recognizes them; those formulas carry a `bbox` and a
  `page`. VLM OCR recognizes formulas in transcribed text without layout, so
  its formulas carry no geometry. Markup extraction (DOCX, PPTX, ODT, EPUB,
  HTML, JATS, LaTeX, Markdown, and related formats) converts embedded math
  to LaTeX, also without geometry.
  """

  @typedoc "A mathematical formula extracted from a document."
  @type t :: %__MODULE__{
          latex: String.t() | nil,
          bbox: Xberg.BoundingBox.t() | nil,
          page: non_neg_integer() | nil
        }

  defstruct latex: nil,
            bbox: nil,
            page: nil
end
