# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.FormattedBlock do
  @moduledoc """
  Block-level element in a Djot document.

  Represents structural elements like headings, paragraphs, lists, code blocks, etc.
  """

  @typedoc "Block-level element in a Djot document."
  @type t :: %__MODULE__{
  block_type: String.t() | nil,
  level: non_neg_integer() | nil,
  inline_content: [Xberg.InlineElement.t()],
  language: String.t() | nil,
  code: String.t() | nil,
  children: [Xberg.FormattedBlock.t()]
  }

  defstruct block_type: :paragraph,
  level: nil,
  inline_content: [],
  language: nil,
  code: nil,
  children: []
end
