# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Formula do
  @moduledoc """
  A mathematical formula detected and recognized in a document.

  Populated by the layout-guided formula pipeline: regions classified as
  `LayoutClass::Formula` are routed to the formula OCR task, which returns the
  LaTeX source for the region. The field is always present on
  [`ExtractedDocument`](super::extraction::ExtractedDocument) but only populated
  when the `layout-detection` feature is active and the document contains
  formula regions.
  """

  @typedoc "A mathematical formula detected and recognized in a document."
  @type t :: %__MODULE__{
          latex: String.t() | nil,
          bbox: Xberg.BoundingBox.t(),
          page: non_neg_integer()
        }

  defstruct latex: nil,
            bbox: nil,
            page: 0
end
