# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ImageMetadataType do
  @moduledoc "Image element metadata."

  @typedoc "Image element metadata."
  @type t :: %__MODULE__{
          src: String.t() | nil,
          alt: String.t() | nil,
          title: String.t() | nil,
          image_type: String.t() | nil
        }

  defstruct src: nil,
            alt: nil,
            title: nil,
            image_type: :data_uri
end
