# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Keyword do
  @moduledoc "Extracted keyword with metadata."

  @typedoc "Extracted keyword with metadata."
  @type t :: %__MODULE__{
  text: String.t() | nil,
  score: float(),
  algorithm: String.t() | nil,
  positions: [non_neg_integer()] | nil
  }

  defstruct text: nil,
  score: 0.0,
  algorithm: :yake,
  positions: nil
end
