# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Keyword do
  @moduledoc "Extracted keyword with metadata."

  @typedoc "Extracted keyword with metadata."
  @type t :: %__MODULE__{
  text: String.t() | nil,
  score: float(),
  algorithm: String.t() | nil,
  positions: [non_neg_integer()] | nil
  }

  defstruct text: nil,
  score: 0.0,
  algorithm: :yake,
  positions: nil
end
