# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.LanguageConfidence do
  @moduledoc """
  Structured per-language detection result: confidence, document share, and script —
  the information the ISO-code-only `detected_languages` list cannot convey (#261).

  Populated by `language_detection` alongside `detected_languages`, with one
  entry per language, in the same order as `detected_languages`.
  """

  @typedoc "Structured per-language detection result: confidence, document share, and script — the information the ISO-code-only `detected_languages` list cannot convey (#261)."
  @type t :: %__MODULE__{
          language: String.t() | nil,
          confidence: float(),
          proportion: float(),
          script: String.t() | nil,
          reliable: boolean()
        }

  defstruct language: nil,
            confidence: 0.0,
            proportion: 0.0,
            script: nil,
            reliable: false
end
