# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.LateInteractionMatch do
  @moduledoc """
  A single document match returned by [`max_sim_rank`], with its position in
  the input and MaxSim score.

  Since v5.0.0.
  """

  @typedoc "A single document match returned by [`max_sim_rank`], with its position in the input and MaxSim score."
  @type t :: %__MODULE__{
  index: non_neg_integer(),
  score: float()
  }

  defstruct index: 0,
  score: 0.0
end
