# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.LayoutDetection do
  @moduledoc "A single layout detection result."

  @typedoc "A single layout detection result."
  @type t :: %__MODULE__{
  class_name: String.t() | nil,
  confidence: float(),
  bbox: Xberg.BBox.t()
  }

  defstruct class_name: :caption,
  confidence: 0.0,
  bbox: nil
end
