# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.LayoutDetection do
  @moduledoc "A single layout detection result."

  @typedoc "A single layout detection result."
  @type t :: %__MODULE__{
  class_name: String.t() | nil,
  confidence: float(),
  bbox: Xberg.BBox.t()
  }

  defstruct class_name: :caption,
  confidence: 0.0,
  bbox: nil
end
