# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.LinkMetadata do
  @moduledoc "Link element metadata."

  @typedoc "Link element metadata."
  @type t :: %__MODULE__{
  href: String.t() | nil,
  text: String.t() | nil,
  title: String.t() | nil,
  link_type: String.t() | nil,
  rel: [String.t()]
  }

  defstruct href: nil,
  text: nil,
  title: nil,
  link_type: :anchor,
  rel: []
end
