# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.LinkMetadata do
  @moduledoc "Link element metadata."

  @typedoc "Link element metadata."
  @type t :: %__MODULE__{
  href: String.t() | nil,
  text: String.t() | nil,
  title: String.t() | nil,
  link_type: String.t() | nil,
  rel: [String.t()]
  }

  defstruct href: nil,
  text: nil,
  title: nil,
  link_type: :anchor,
  rel: []
end
