# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ListIndentType do
  @moduledoc """
  List indentation character type.

  Controls whether list items are indented with spaces or tabs.
  """

  @typedoc "List indentation character type."
  @type t :: :spaces | :tabs

  @spaces :spaces
  @tabs :tabs

  @doc "Use spaces for indentation. Default. Width controlled by `list_indent_width`."
  @spec spaces() :: t()
  def spaces, do: @spaces
  @doc "Use tabs for indentation."
  @spec tabs() :: t()
  def tabs, do: @tabs
end
