# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ListIndentType do
  @moduledoc """
  List indentation character type.

  Controls whether list items are indented with spaces or tabs.
  """

  @typedoc "List indentation character type."
  @type t :: :spaces | :tabs

  @spaces :spaces
  @tabs :tabs

  @doc "Use spaces for indentation. Default. Width controlled by `list_indent_width`."
  @spec spaces() :: t()
  def spaces, do: @spaces
  @doc "Use tabs for indentation."
  @spec tabs() :: t()
  def tabs, do: @tabs
end
