# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ModelPaths do
  @moduledoc "Combined paths to all models needed for OCR (backward compatibility)."

  @typedoc "Combined paths to all models needed for OCR (backward compatibility)."
  @type t :: %__MODULE__{
          det_model: String.t() | nil,
          cls_model: String.t() | nil,
          rec_model: String.t() | nil,
          dict_file: String.t() | nil
        }

  defstruct det_model: nil,
            cls_model: nil,
            rec_model: nil,
            dict_file: nil
end
