# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.OcrPipelineConfig do
  @moduledoc """
  Multi-backend OCR pipeline with quality-based fallback.

  Backends are tried in priority order (highest first). After each backend
  produces output, quality is evaluated. If it meets `quality_thresholds.pipeline_min_quality`,
  the result is accepted. Otherwise the next backend is tried; if none clears the
  threshold, an internal selection policy derived from the `OcrConfig` decides which
  stage's result is returned as the best effort (`vlm_fallback` pipelines prefer their
  last non-empty stage; explicit and classical pipelines stay score-based).
  """

  @typedoc "Multi-backend OCR pipeline with quality-based fallback."
  @type t :: %__MODULE__{
          stages: [Xberg.OcrPipelineStage.t()],
          quality_thresholds: Xberg.OcrQualityThresholds.t()
        }

  defstruct stages: [],
            quality_thresholds: nil
end
