# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.OcrRotation do
  @moduledoc "Rotation information for an OCR element."

  @typedoc "Rotation information for an OCR element."
  @type t :: %__MODULE__{
  angle_degrees: float(),
  confidence: float() | nil
  }

  defstruct angle_degrees: 0.0,
  confidence: nil
end
