# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.OcrTableBoundingBox do
  @moduledoc "Bounding box for an OCR-detected table in pixel coordinates."

  @typedoc "Bounding box for an OCR-detected table in pixel coordinates."
  @type t :: %__MODULE__{
  left: non_neg_integer(),
  top: non_neg_integer(),
  right: non_neg_integer(),
  bottom: non_neg_integer()
  }

  defstruct left: 0,
  top: 0,
  right: 0,
  bottom: 0
end
