# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageClassificationConfig do
  @moduledoc "Configuration for the page-classification post-processor."

  @typedoc "Configuration for the page-classification post-processor."
  @type t :: %__MODULE__{
  prompt_template: String.t() | nil,
  labels: [String.t()],
  multi_label: boolean(),
  llm: Xberg.LlmConfig.t()
  }

  defstruct prompt_template: nil,
  labels: [],
  multi_label: false,
  llm: nil
end
