# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageSpan do
  @moduledoc """
  A single page covered by a chunk, with an optional bounding box on that page.

  See [`ChunkMetadata::page_spans`] (#1295) for population semantics.
  """

  @typedoc "A single page covered by a chunk, with an optional bounding box on that page."
  @type t :: %__MODULE__{
          page: non_neg_integer(),
          bbox: Xberg.BoundingBox.t() | nil
        }

  defstruct page: 0,
            bbox: nil
end
