# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageInfo do
  @moduledoc """
  Metadata for individual page/slide/sheet.

  Captures per-page information including dimensions, content counts,
  and visibility state (for presentations).
  """

  @typedoc "Metadata for individual page/slide/sheet."
  @type t :: %__MODULE__{
          number: non_neg_integer(),
          title: String.t() | nil,
          image_count: non_neg_integer() | nil,
          table_count: non_neg_integer() | nil,
          hidden: boolean() | nil,
          is_blank: boolean() | nil,
          has_vector_graphics: boolean()
        }

  defstruct number: 0,
            title: nil,
            image_count: nil,
            table_count: nil,
            hidden: nil,
            is_blank: nil,
            has_vector_graphics: false
end
