# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageClassificationConfig do
  @moduledoc "Configuration for the page-classification post-processor."

  @typedoc "Configuration for the page-classification post-processor."
  @type t :: %__MODULE__{
  prompt_template: String.t() | nil,
  labels: [String.t()],
  multi_label: boolean(),
  llm: Xberg.LlmConfig.t()
  }

  defstruct prompt_template: nil,
  labels: [],
  multi_label: false,
  llm: nil
end
