# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageClassification do
  @moduledoc "Classification result for a single page."

  @typedoc "Classification result for a single page."
  @type t :: %__MODULE__{
  page_number: non_neg_integer(),
  labels: [Xberg.ClassificationLabel.t()]
  }

  defstruct page_number: 0,
  labels: []
end
