# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageRange do
  @moduledoc "Page range for a chunk (0-indexed, inclusive)."

  @typedoc "Page range for a chunk (0-indexed, inclusive)."
  @type t :: %__MODULE__{
          start: non_neg_integer(),
          end: non_neg_integer()
        }

  defstruct start: 0,
            end: 0
end
