# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageClassification do
  @moduledoc "Classification result for a single page."

  @typedoc "Classification result for a single page."
  @type t :: %__MODULE__{
          page_number: non_neg_integer(),
          labels: [Xberg.ClassificationLabel.t()]
        }

  defstruct page_number: 0,
            labels: []
end
