# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageSpan do
  @moduledoc """
  A single page covered by a chunk, with an optional bounding box on that page.

  See [`ChunkMetadata::page_spans`] (#1295) for population semantics.
  """

  @typedoc "A single page covered by a chunk, with an optional bounding box on that page."
  @type t :: %__MODULE__{
  page: non_neg_integer(),
  bbox: Xberg.BoundingBox.t() | nil
  }

  defstruct page: 0,
  bbox: nil
end
