# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageStructure do
  @moduledoc """
  Unified page structure for documents.

  Supports different page types (PDF pages, PPTX slides, Excel sheets)
  with character offset boundaries for chunk-to-page mapping.
  """

  @typedoc "Unified page structure for documents."
  @type t :: %__MODULE__{
  total_count: non_neg_integer(),
  unit_type: String.t() | nil,
  boundaries: [Xberg.PageBoundary.t()] | nil,
  pages: [Xberg.PageInfo.t()] | nil
  }

  defstruct total_count: 0,
  unit_type: :page,
  boundaries: nil,
  pages: nil
end
