# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageSpan do
  @moduledoc """
  A single page covered by a chunk, with an optional bounding box on that page.

  See [`ChunkMetadata::page_spans`] (#1295) for population semantics.
  """

  @typedoc "A single page covered by a chunk, with an optional bounding box on that page."
  @type t :: %__MODULE__{
  page: non_neg_integer(),
  bbox: Xberg.BoundingBox.t() | nil
  }

  defstruct page: 0,
  bbox: nil
end
