# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageClassificationConfig do
  @moduledoc "Configuration for the page-classification post-processor."

  @typedoc "Configuration for the page-classification post-processor."
  @type t :: %__MODULE__{
          prompt_template: String.t() | nil,
          labels: [String.t()],
          multi_label: boolean(),
          llm: Xberg.LlmConfig.t()
        }

  defstruct prompt_template: nil,
            labels: [],
            multi_label: false,
            llm: nil
end
