# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:11dafcefdb4aa6193fa6eab2e2eb184294f2729019f2af245e2a50346ad7250f
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PageOcrConfidence do
  @moduledoc """
  Aggregate OCR legibility score for a page, reported by the backend that produced its text.

  This is distinct from [`OcrConfidence`], which scores a single detected element (a word or
  line) using detection/recognition confidence from the OCR engine itself. `PageOcrConfidence`
  is a page-level summary computed after noise filtering, intended for triage of which pages
  are worth a closer look, not for comparing OCR engines against each other.
  """

  @typedoc "Aggregate OCR legibility score for a page, reported by the backend that produced its text."
  @type t :: %__MODULE__{
          score: float() | nil,
          word_count: non_neg_integer(),
          backend: String.t() | nil
        }

  defstruct score: nil,
            word_count: 0,
            backend: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
