# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageUnitType do
  @moduledoc """
  Type of paginated unit in a document.

  Distinguishes between different types of "pages" (PDF pages, presentation slides, spreadsheet sheets).
  """

  @typedoc "Type of paginated unit in a document."
  @type t :: :page | :slide | :sheet

  @page :page
  @slide :slide
  @sheet :sheet

  @doc "Standard document pages (PDF, DOCX, images)"
  @spec page() :: t()
  def page, do: @page
  @doc "Presentation slides (PPTX, ODP)"
  @spec slide() :: t()
  def slide, do: @slide
  @doc "Spreadsheet sheets (XLSX, ODS)"
  @spec sheet() :: t()
  def sheet, do: @sheet
end
