# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageRange do
  @moduledoc "Page range for a chunk (0-indexed, inclusive)."

  @typedoc "Page range for a chunk (0-indexed, inclusive)."
  @type t :: %__MODULE__{
  start: non_neg_integer(),
  end: non_neg_integer()
  }

  defstruct start: 0,
  end: 0
end
