# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PostProcessorConfig do
  @moduledoc "Post-processor configuration."

  @typedoc "Post-processor configuration."
  @type t :: %__MODULE__{
  enabled: boolean(),
  enabled_processors: [String.t()] | nil,
  disabled_processors: [String.t()] | nil,
  enabled_set: [String.t()] | nil,
  disabled_set: [String.t()] | nil
  }

  defstruct enabled: true,
  enabled_processors: nil,
  disabled_processors: nil,
  enabled_set: nil,
  disabled_set: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
