# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PreprocessingPreset do
  @moduledoc """
  HTML preprocessing aggressiveness level.

  Controls the extent of cleanup performed before conversion. Higher levels remove more elements.
  """

  @typedoc "HTML preprocessing aggressiveness level."
  @type t :: :minimal | :standard | :aggressive

  @minimal :minimal
  @standard :standard
  @aggressive :aggressive

  @doc "Minimal cleanup. Remove only essential noise (scripts, styles)."
  @spec minimal() :: t()
  def minimal, do: @minimal
  @doc "Standard cleanup. Default. Removes navigation, forms, and other auxiliary content."
  @spec standard() :: t()
  def standard, do: @standard
  @doc "Aggressive cleanup. Remove extensive non-content elements and structure."
  @spec aggressive() :: t()
  def aggressive, do: @aggressive
end
