# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ProcessingWarning do
  @moduledoc """
  A non-fatal warning from a processing pipeline stage.

  Captures errors from optional features that don't prevent extraction
  but may indicate degraded results.
  """

  @typedoc "A non-fatal warning from a processing pipeline stage."
  @type t :: %__MODULE__{
  source: String.t() | nil,
  message: String.t() | nil
  }

  defstruct source: nil,
  message: nil
end
