# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PstMetadata do
  @moduledoc "Outlook PST archive metadata."

  @typedoc "Outlook PST archive metadata."
  @type t :: %__MODULE__{
  message_count: non_neg_integer()
  }

  defstruct message_count: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
