# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.QrCode do
  @moduledoc "One QR code decoded from an extracted image."

  @typedoc "One QR code decoded from an extracted image."
  @type t :: %__MODULE__{
  payload: String.t() | nil,
  confidence: float() | nil,
  bbox: Xberg.QrBoundingBox.t() | nil
  }

  defstruct payload: nil,
  confidence: nil,
  bbox: nil
end
