# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.QrCode do
  @moduledoc "One QR code decoded from an extracted image."

  @typedoc "One QR code decoded from an extracted image."
  @type t :: %__MODULE__{
  payload: String.t() | nil,
  confidence: float() | nil,
  bbox: Xberg.QrBoundingBox.t() | nil
  }

  defstruct payload: nil,
  confidence: nil,
  bbox: nil
end
