# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.RakeParams do
  @moduledoc "RAKE-specific parameters."

  @typedoc "RAKE-specific parameters."
  @type t :: %__MODULE__{
          min_word_length: non_neg_integer(),
          max_words_per_phrase: non_neg_integer()
        }

  defstruct min_word_length: 1,
            max_words_per_phrase: 3

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
