# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.RedactionPattern do
  @moduledoc """
  One user-supplied regex pattern to redact.

  The pattern is compiled with the Rust `regex` crate (no look-around). Case
  sensitivity is encoded in the pattern via the `(?i)` inline flag when
  [`Self::case_sensitive`] is `false`.
  """

  @typedoc "One user-supplied regex pattern to redact."
  @type t :: %__MODULE__{
  label: String.t() | nil,
  pattern: String.t() | nil,
  case_sensitive: boolean()
  }

  defstruct label: nil,
  pattern: nil,
  case_sensitive: false
end
