# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.RedactionTerm do
  @moduledoc """
  One user-supplied literal term to redact.

  Matched as a regex-escaped substring (so callers do not need to escape
  metacharacters themselves). Case-insensitive by default — set
  [`Self::case_sensitive`] to `true` for exact byte-match semantics.
  """

  @typedoc "One user-supplied literal term to redact."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          value: String.t() | nil,
          case_sensitive: boolean()
        }

  defstruct label: nil,
            value: nil,
            case_sensitive: false
end
