# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.RevisionKind do
  @moduledoc "Semantic classification of a tracked change."

  @typedoc "Semantic classification of a tracked change."
  @type t :: :insertion | :deletion | :format_change | :comment

  @insertion :insertion
  @deletion :deletion
  @format_change :format_change
  @comment :comment

  @doc "Text or content was inserted."
  @spec insertion() :: t()
  def insertion, do: @insertion
  @doc "Text or content was deleted."
  @spec deletion() :: t()
  def deletion, do: @deletion
  @doc "Run-level formatting (font, size, colour, …) was changed."
  @spec format_change() :: t()
  def format_change, do: @format_change
  @doc "A reviewer comment or annotation."
  @spec comment() :: t()
  def comment, do: @comment
end
