# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.SparseEmbedding do
  @moduledoc """
  A sparse learned embedding: vocabulary term indices and their weights.

  `indices` are ascending vocabulary token ids; `values[i]` is the weight for
  `indices[i]`. The two arrays always have equal length. Only strictly-positive
  terms are retained, so the representation is genuinely sparse.

  Since v5.0.0.
  """

  @typedoc "A sparse learned embedding: vocabulary term indices and their weights."
  @type t :: %__MODULE__{
  indices: [non_neg_integer()],
  values: [float()]
  }

  defstruct indices: [],
  values: []
end
