# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.SupportedFormat do
  @moduledoc """
  A supported document format entry.

  Represents a file extension and its corresponding MIME type that Xberg can process.
  """

  @typedoc "A supported document format entry."
  @type t :: %__MODULE__{
  extension: String.t() | nil,
  mime_type: String.t() | nil
  }

  defstruct extension: nil,
  mime_type: nil
end
