# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TableOverlapPreference do
  @moduledoc """
  How to resolve overlapping native vs layout (TATR/SLANeXT) tables.

  When both native oxide detection and the layout table model produce a table for
  the same page region, one must be dropped. This controls which one wins. Wire
  format is snake_case in all serializers (JSON, TOML, YAML).
  """

  @typedoc "How to resolve overlapping native vs layout (TATR/SLANeXT) tables."
  @type t :: :content | :native | :layout

  @content :content
  @native :native
  @layout :layout

  @doc "Keep whichever table carries more content (cell count + markdown length). This is the historical default. TATR/SLANeXT tables usually recognize more cells and therefore win, which maximizes table-structure F1 but can lower text F1 when the recognized cell reflow diverges from the source reading order."
  @spec content() :: t()
  def content, do: @content

  @doc "Prefer the native oxide table when it overlaps a layout table. Native tables preserve the source reading order, which scores higher on text F1 for documents where the layout model's cell reflow diverges from the ground truth."
  @spec native() :: t()
  def native, do: @native
  @doc "Prefer the layout (TATR/SLANeXT) table when it overlaps a native table."
  @spec layout() :: t()
  def layout, do: @layout
end
