# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TextAnnotation do
  @moduledoc """
  Inline text annotation — byte-range based formatting and links.

  Annotations reference byte offsets into the node's text content,
  enabling precise identification of formatted regions.
  """

  @typedoc "Inline text annotation — byte-range based formatting and links."
  @type t :: %__MODULE__{
  start: non_neg_integer(),
  end: non_neg_integer(),
  kind: String.t() | nil
  }

  defstruct start: 0,
  end: 0,
  kind: :bold
end
