# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TranslationConfig do
  @moduledoc "Configuration for the translation post-processor."

  @typedoc "Configuration for the translation post-processor."
  @type t :: %__MODULE__{
  target_lang: String.t() | nil,
  source_lang: String.t() | nil,
  preserve_markup: boolean(),
  llm: Xberg.LlmConfig.t()
  }

  defstruct target_lang: nil,
  source_lang: nil,
  preserve_markup: false,
  llm: nil
end
