# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TreeSitterConfig do
  @moduledoc """
  Configuration for tree-sitter language pack integration.

  Controls grammar download behavior and code analysis options.

  # Example (TOML)

  ```toml
  [tree_sitter]
  languages = ["python", "rust"]
  groups = ["web"]

  [tree_sitter.process]
  structure = true
  comments = true
  docstrings = true
  ```
  """

  @typedoc "Configuration for tree-sitter language pack integration."
  @type t :: %__MODULE__{
  enabled: boolean(),
  cache_dir: String.t() | nil,
  languages: [String.t()] | nil,
  groups: [String.t()] | nil,
  process: Xberg.TreeSitterProcessConfig.t()
  }

  defstruct enabled: true,
  cache_dir: nil,
  languages: nil,
  groups: nil,
  process: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
