<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\Xberg;
use Xberg\ExtractionConfig;

/** E2e tests for category: tokenizer_backend_management. */
final class TokenizerBackendManagementTest extends TestCase
{

    /** Clear all tokenizer backends and verify list is empty */
    public function test_tokenizer_backends_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::clearTokenizerBackends();


    }


    /** List all registered tokenizer backends */
    public function test_tokenizer_backends_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listTokenizerBackends();


    }

}
