<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\Xberg;
use Xberg\ExtractionConfig;

/** E2e tests for category: validator_management. */
final class ValidatorManagementTest extends TestCase
{

    /** Clear all validators and verify list is empty */
    public function test_validators_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::clearValidators();


    }


    /** List all registered validators */
    public function test_validators_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listValidators();


    }

}
