<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5b65fe8ac640bf4cdf1e1a281c4b41b6d0d521d562ffcfc7007265ad142fb846
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\Xberg;
use Xberg\ExtractionConfig;

/** E2e tests for category: validator_management. */
final class ValidatorManagementTest extends TestCase
{

    /** Clear all validators and verify list is empty */
    public function test_validators_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::clearValidators();


    }


    /** List all registered validators */
    public function test_validators_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listValidators();


    }

}
