// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A cache read or write operation failed.
/// </summary>
public class CacheException : XbergErrorException {
  public CacheException(string message) : base(message) {}

  public CacheException(string message, Exception innerException)
      : base(message, innerException) {}
}
