// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Invalid configuration value.
/// </summary>
public class ConfigErrorException : HeuristicsErrorException
{
    public ConfigErrorException(string message) : base(message) { }

    public ConfigErrorException(string message, Exception innerException) : base(message, innerException) { }
}
