// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The file validates but cannot be deserialized into `Preset`.
/// </summary>
public class DeserializeException : LoadErrorException
{
    public DeserializeException(string message) : base(message) { }

    public DeserializeException(string message, Exception innerException) : base(message, innerException) { }
}
