// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;
/// <summary>
/// How the extracted text was produced.
/// </summary>
[JsonConverter(typeof(ExtractionMethodJsonConverter))]
public enum ExtractionMethod {
  /// <summary>
  /// Text extracted directly from the document's native format (no OCR).
  /// </summary>
  [JsonPropertyName("native")] Native,
  /// <summary>
  /// All text was obtained via OCR (e.g. scanned image-only PDF).
  /// </summary>
  [JsonPropertyName("ocr")] Ocr,
  /// <summary>
  /// Text came from a combination of native extraction and OCR.
  /// </summary>
  [JsonPropertyName("mixed")] Mixed,
}

/// <summary>
/// Custom JSON converter for <see cref="ExtractionMethod"/> that respects
/// explicit variant names.
/// </summary>
internal sealed class ExtractionMethodJsonConverter
    : JsonConverter<ExtractionMethod> {
  public override ExtractionMethod Read(ref Utf8JsonReader reader,
                                        Type typeToConvert,
                                        JsonSerializerOptions options) {
    var value = reader.GetString();
    return value switch {
      "native" => ExtractionMethod.Native, "ocr" => ExtractionMethod.Ocr,
      "mixed" => ExtractionMethod.Mixed,
      _ => throw new JsonException($"Unknown ExtractionMethod value: {value}")
    };
  }

  public override void Write(Utf8JsonWriter writer, ExtractionMethod value,
                             JsonSerializerOptions options) {
    var str = value switch {
      ExtractionMethod.Native => "native", ExtractionMethod.Ocr => "ocr",
      ExtractionMethod.Mixed => "mixed",
      _ => throw new JsonException($"Unknown ExtractionMethod value: {value}")
    };
    writer.WriteStringValue(str);
  }
}
