// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9c2ad40b63da4ac149601bc4a245a2fb674f5f069aef5e5a1027cd6c04bdb57b
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;
/// <summary>
/// Formula recognition model selection.
/// </summary>
[JsonConverter(typeof(FormulaModelJsonConverter))]
public enum FormulaModel
{
    /// <summary>
    /// RapidLaTeXOCR (MIT, pix2tex-derived): resizer + encoder + decoder ONNX,
    /// ~180 MB total, downloaded on demand.
    /// </summary>
    [JsonPropertyName("latex_ocr")]
    LatexOcr,
}


/// <summary>
/// Custom JSON converter for <see cref="FormulaModel"/> that respects explicit variant names.
/// </summary>
internal sealed class FormulaModelJsonConverter : JsonConverter<FormulaModel>
{
    public override FormulaModel Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "latex_ocr" => FormulaModel.LatexOcr,
            _ => throw new JsonException($"Unknown FormulaModel value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, FormulaModel value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            FormulaModel.LatexOcr => "latex_ocr",
            _ => throw new JsonException($"Unknown FormulaModel value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
