// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:aa240cde73f37b505aed63150346f5b94d4ccbc7f7dd9656f89d56e568d57758
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// A mathematical formula extracted from a document.
///
/// Three kinds of sources populate this type. Layout-guided OCR detects
/// formula regions and recognizes them; those formulas carry a `bbox` and a
/// `page`. VLM OCR recognizes formulas in transcribed text without layout, so
/// its formulas carry no geometry. Markup extraction (DOCX, PPTX, ODT, EPUB,
/// HTML, JATS, LaTeX, Markdown, and related formats) converts embedded math
/// to LaTeX, also without geometry.
/// </summary>
public sealed record Formula
{
    /// <summary>
    /// LaTeX source of the formula, without surrounding `$$` delimiters.
    ///
    /// Markup converters and formula OCR produce real LaTeX. The native PDF
    /// layout path stores the plain text of a detected formula region, which
    /// keeps the original Unicode math characters instead of LaTeX commands.
    /// To render the formula in Markdown or other formats, wrap it in `$$..$$`.
    /// </summary>
    [JsonPropertyName("latex")]
    public required string Latex { get; init; }

    /// <summary>
    /// Bounding box of the formula region on its page. `None` for markup sources.
    ///
    /// PDF OCR sources report PDF point coordinates with the origin at the
    /// bottom-left of the page, comparable to native PDF geometry. Image
    /// sources, and PDF pages whose geometry is unavailable, report pixels of
    /// the image the OCR backend saw. The C FFI reports an absent bbox as a
    /// null pointer.
    /// </summary>
    [JsonPropertyName("bbox")]
    public BoundingBox? Bbox { get; init; } = null;

    /// <summary>
    /// 1-indexed page number the formula appears on. `None` when the source
    /// format has no page concept. The C FFI reports an absent page as `0`.
    /// </summary>
    [JsonPropertyName("page")]
    public uint? Page { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="Formula"/> from a JSON string.
    /// </summary>
    /// <exception cref="XbergException">When the JSON cannot be deserialised.</exception>
    public static Formula FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<Formula>(json, JsonOptions)
                ?? throw new XbergException($"Failed to parse Formula from JSON: deserializer returned null");
        }
        catch (XbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new XbergException($"Failed to parse Formula from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };
}
