// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors that can occur during heuristics analysis.
/// </summary>
public class HeuristicsErrorException : XbergException {
  public HeuristicsErrorException(string message) : base(message) {}

  public HeuristicsErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
