// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A required optional system dependency (e.g. `tesseract`) was not found.
/// </summary>
public class MissingDependencyException : XbergErrorException
{
    public MissingDependencyException(string message) : base(message) { }

    public MissingDependencyException(string message, Exception innerException) : base(message, innerException) { }
}
