// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A required optional system dependency (e.g. `tesseract`) was not found.
/// </summary>
public class MissingDependencyException : XbergErrorException {
  public MissingDependencyException(string message) : base(message) {}

  public MissingDependencyException(string message, Exception innerException)
      : base(message, innerException) {}
}
