// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A required optional system dependency (e.g. `tesseract`) was not found.
/// </summary>
public class MissingDependencyException : XbergErrorException
{
    public MissingDependencyException(string message) : base(message) { }

    public MissingDependencyException(string message, Exception innerException) : base(message, innerException) { }
}
