// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// An OCR engine returned an error or produced unusable output.
/// </summary>
public class OcrException : XbergErrorException {
  public OcrException(string message) : base(message) {}

  public OcrException(string message, Exception innerException)
      : base(message, innerException) {}
}
