// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Document parsing failed (e.g. corrupt file, unsupported format feature).
/// </summary>
public class ParsingException : XbergErrorException {
  public ParsingException(string message) : base(message) {}

  public ParsingException(string message, Exception innerException)
      : base(message, innerException) {}
}
