// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A registered plugin returned an error during extraction.
/// </summary>
public class PluginException : XbergErrorException
{
    public PluginException(string message) : base(message) { }

    public PluginException(string message, Exception innerException) : base(message, innerException) { }
}
