// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A custom schema override was supplied but is not a JSON object.
/// </summary>
public class SchemaNotObjectException : ResolveErrorException
{
    public SchemaNotObjectException(string message) : base(message) { }

    public SchemaNotObjectException(string message, Exception innerException) : base(message, innerException) { }
}
