// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A custom schema override was supplied but is not a JSON object.
/// </summary>
public class SchemaNotObjectException : ResolveErrorException {
  public SchemaNotObjectException(string message) : base(message) {}

  public SchemaNotObjectException(string message, Exception innerException)
      : base(message, innerException) {}
}
