// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A security policy was violated (e.g. zip bomb, oversized archive).
/// </summary>
public class SecurityException : XbergErrorException {
  public SecurityException(string message) : base(message) {}

  public SecurityException(string message, Exception innerException)
      : base(message, innerException) {}
}
