// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The document's MIME type is not supported by any registered extractor.
/// </summary>
public class UnsupportedFormatException : XbergErrorException {
  public UnsupportedFormatException(string message) : base(message) {}

  public UnsupportedFormatException(string message, Exception innerException)
      : base(message, innerException) {}
}
