// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
#nullable enable

using System;

namespace Xberg;

public class XbergException : Exception {
  public int Code { get; }

  public XbergException(int code, string message) : base(message) {
    Code = code;
  }

  public XbergException(string message) : base(message) { Code = 0; }

  public XbergException(string message, Exception innerException)
      : base(message, innerException) {
    Code = 0;
  }
}
