// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5bff8112f303670f5a54e531d3cb522ee598d5f9497b88b9ee7b2fddcd1f4a0f
#nullable enable

using System;

namespace Xberg;

public class XbergException : Exception
{
    public int Code { get; }

    public XbergException(int code, string message) : base(message)
    {
        Code = code;
    }

    public XbergException(string message) : base(message)
    {
        Code = 0;
    }

    public XbergException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
