// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
#nullable enable

using System;

namespace Xberg;

public class XbergException : Exception
{
    public int Code { get; }

    public XbergException(int code, string message) : base(message)
    {
        Code = code;
    }

    public XbergException(string message) : base(message)
    {
        Code = 0;
    }

    public XbergException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
