# Generated by alef. Do not edit by hand.
# alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
# Keep generated public API for consumers using R8/ProGuard.
-keep class io.xberg.** { *; }
