# Generated by alef. Do not edit by hand.
# alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
# Keep generated public API for consumers using R8/ProGuard.
-keep class io.xberg.** { *; }
