// Generated by alef. Do not edit by hand.
// alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Chunk-classification enrichment knob: how to multi-label individual chunks.
 *
 * Operates on `ExtractedDocument.chunks` in place — the caller must have
 * already produced chunks (e.g. via `ExtractionConfig.chunking`) for this
 * stage to have any effect; a document with no chunks is a no-op.
 */
data class ChunkClassificationEnrichmentConfig(
    /** Label-definition set and LLM/batching settings for the chunk-classification stage. */
    val config: ChunkClassificationConfig,
)
