// Generated by alef. Do not edit by hand.
// alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * A text chunk with optional embedding and metadata.
 *
 * Chunks are created when chunking is enabled in `ExtractionConfig`. Each chunk
 * contains the text content, optional embedding vector (if embedding generation
 * is configured), and metadata about its position in the document.
 */
data class Chunk(
    /** The text content of this chunk. */
    val content: String,
    /**
     * Semantic structural classification of this chunk.
     *
     * Assigned by the heuristic classifier based on content patterns and
     * heading context. Defaults to `ChunkType.Unknown` when no rule matches.
     */
    val chunkType: ChunkType,
    /**
     * Optional embedding vector for this chunk.
     *
     * Only populated when `EmbeddingConfig` is provided in chunking configuration.
     * The dimensionality depends on the chosen embedding model.
     */
    val embedding: List<Float>? = null,
    /**
     * Optional sparse (SPLADE) learned embedding for this chunk.
     *
     * Only populated when sparse-embedding generation is configured for chunking.
     * `null` otherwise, including on builds without the `sparse-embeddings` feature.
     *
     * Uses the crate-root `SparseEmbedding` alias rather than
     * `crate.sparse_embeddings.SparseEmbedding` directly: the `sparse_embeddings`
     * module itself only compiles under `sparse-embeddings`/`sparse-embedding-presets`,
     * while the crate-root alias is always defined (a field-compatible stub on builds
     * without either feature), so this field — and `Chunk` itself — compiles on every
     * feature combination, including the crate's default features.
     */
    val sparseEmbedding: SparseEmbedding? = null,
    /**
     * Optional ColBERT-style multi-vector (late-interaction) embedding for this chunk.
     *
     * Only populated when late-interaction embedding generation is configured for
     * chunking. `null` otherwise, including on builds without the `late-interaction`
     * feature.
     *
     * Uses the crate-root `MultiVectorEmbedding` alias for the same reason
     * `sparse_embedding` uses `SparseEmbedding` — see that field's docs.
     */
    val lateInteraction: MultiVectorEmbedding? = null,
    /** Metadata about this chunk's position and properties. */
    val metadata: ChunkMetadata,
)
