// Generated by alef. Do not edit by hand.
// alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * An XML-style attribute attached to an `Element` node.
 *
 * Populated only for `CodeDataNodeKind.Element`; always empty for `KeyValue` and
 * `Sequence` nodes.
 */
data class CodeDataAttribute(
    /** Attribute name (e.g. `"class"`, `"href"`). */
    val name: String,
    /** Attribute value as a raw string (quotes stripped). */
    val value: String,
    /** Inclusive start byte offset of the `name="value"` attribute token. */
    val byteStart: Long,
    /** Exclusive end byte offset of the `name="value"` attribute token. */
    val byteEnd: Long,
)
