// Generated by alef. Do not edit by hand.
// alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Unified extraction input for all public extraction entry points. */
data class ExtractInput(
    /** Source kind. `bytes` requires `bytes`; `uri` requires `uri`. */
    val kind: ExtractInputKind = ExtractInputKind.URI,
    /** Raw bytes for `kind = "bytes"`. */
    val bytes: ByteArray? = null,
    /** Local path, `file://` URI, or HTTP(S) URL for `kind = "uri"`. */
    val uri: String? = null,
    /** MIME type hint. */
    val mimeType: String? = null,
    /** Filename hint used for MIME detection and metadata. */
    val filename: String? = null,
    /** Per-input extraction overrides. */
    val config: FileExtractionConfig? = null,
)
