// Generated by alef. Do not edit by hand.
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Source kind for `ExtractInput`. */
enum class ExtractInputKind {
    /** Raw in-memory bytes. */
    @com.fasterxml.jackson.annotation.JsonProperty("bytes") BYTES,
    /** A filesystem path, `file://` URI, or HTTP(S) URL. */
    @com.fasterxml.jackson.annotation.JsonProperty("uri") URI;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
    when (this) {
        BYTES -> "bytes"
        URI -> "uri"
    }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): ExtractInputKind =
        when (value) {
            "bytes" -> BYTES
            "uri" -> URI
            else -> throw IllegalArgumentException("Unknown ExtractInputKind value: $value")
        }
    }
}
