// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Formula recognition model selection. */
enum class FormulaModel {
    /**
     * RapidLaTeXOCR (MIT, pix2tex-derived): resizer + encoder + decoder ONNX,
     * ~180 MB total, downloaded on demand.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("latex_ocr") LATEX_OCR;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            LATEX_OCR -> "latex_ocr"
        }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): FormulaModel =
            when (value) {
                "latex_ocr" -> LATEX_OCR
                else -> throw IllegalArgumentException("Unknown FormulaModel value: $value")
            }
    }
}
