// Generated by alef. Do not edit by hand.
// alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Individual grid cell with position and span metadata. */
data class GridCell(
    /** Cell text content. */
    val content: String,
    /** Zero-indexed row position. */
    val row: Int,
    /** Zero-indexed column position. */
    val col: Int,
    /** Number of rows this cell spans. */
    val rowSpan: Int,
    /** Number of columns this cell spans. */
    val colSpan: Int,
    /** Whether this is a header cell. */
    val isHeader: Boolean,
    /** Bounding box for this cell (if available). */
    val bbox: BoundingBox? = null,
)
