// Generated by alef. Do not edit by hand.
// alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Structured per-language detection result: confidence, document share, and script —
 * the information the ISO-code-only `detected_languages` list cannot convey (#261).
 *
 * Populated by `language_detection` alongside `detected_languages`, with one
 * entry per language, in the same order as `detected_languages`.
 */
data class LanguageConfidence(
    /** ISO 639-3 language code, matching the corresponding entry in `detected_languages`. */
    val language: String,
    /**
     * Confidence for this language, in `[0.0, 1.0]`.
     *
     * In single-language mode this is whatlang's `Info.confidence()` for the whole
     * document. In multi-language mode this is the average whatlang confidence across
     * the document's 200-character chunks that were classified as this language.
     */
    val confidence: Double,
    /**
     * Share of the document's analyzed content classified as this language, in `[0.0, 1.0]`.
     *
     * In single-language mode this is always `1.0`. In multi-language mode this is the
     * fraction of 200-character chunks classified as this language (chunks that did not
     * meet `min_confidence` for any language are excluded from the count but still count
     * toward the denominator).
     */
    val proportion: Double,
    /** Writing system whatlang detected for this language (e.g. `"Latin"`, `"Cyrillic"`). */
    val script: String,
    /**
     * Whether this detection is considered reliable.
     *
     * In single-language mode this is whatlang's own `Info.is_reliable()` (confidence
     * above whatlang's internal 0.9 threshold). In multi-language mode this is the
     * chunk-averaged `confidence` above that same 0.9 threshold, since whatlang's
     * `is_reliable()` only applies to a single detection.
     */
    val reliable: Boolean,
)
