// Generated by alef. Do not edit by hand.
// alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Static metadata for a bundled ColBERT preset (WASM/Android-safe, no ORT).
 *
 * Since v5.0.
 */
data class LateInteractionPreset(
    /** Stable preset name referenced from config. */
    val name: String,
    /** HuggingFace repository hosting the ONNX model. */
    val modelRepo: String,
    /** Path to the ONNX file within the repo. */
    val modelFile: String,
    /** Sibling files that must be downloaded alongside `model_file`. */
    val additionalFiles: List<String> = emptyList(),
    /** Maximum document token sequence length. */
    val maxLength: Long,
    /** Fixed padded query length (ColBERT query augmentation). */
    val queryMaxLength: Long,
    /** Per-token embedding dimensionality. */
    val dim: Long,
    /** Human-readable description. */
    val description: String,
)
