// Generated by alef. Do not edit by hand.
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Configuration for an LLM provider/model via liter-llm.
 *
 * Each feature (VLM OCR, VLM embeddings, structured extraction) carries
 * its own `LlmConfig`, allowing different providers per feature.
 *
 * `Debug` is implemented by hand so `api_key`, header values, and the AWS
 * credentials in `BedrockConfig` are never printed.
 */
data class LlmConfig(
    /**
     * Provider/model string using liter-llm routing format.
     *
     * Examples: `"openai/gpt-4o"`, `"anthropic/claude-sonnet-4-20250514"`,
     * `"groq/llama-3.1-70b-versatile"`.
     */
    val model: String = "",
    /**
     * API key for the provider. When `null`, liter-llm falls back to
     * the provider's standard environment variable (e.g., `OPENAI_API_KEY`).
     */
    val apiKey: String? = null,
    /** Custom base URL override for the provider endpoint. */
    val baseUrl: String? = null,
    /**
     * Request timeout in seconds. When `null`, liter-llm's built-in 60s default
     * applies, except the VLM OCR path which uses a 300s default (a single page
     * image transcription routinely exceeds 60s). Set explicitly to override.
     */
    val timeoutSecs: Long? = null,
    /** Maximum retry attempts (default: 3). */
    val maxRetries: Int? = null,
    /** Sampling temperature for generation tasks. */
    val temperature: Double? = null,
    /** Maximum tokens to generate. */
    val maxTokens: Long? = null,
    /**
     * Whether liter-llm should load provider credentials from environment variables.
     *
     * Mirrors liter-llm's `ClientConfigBuilder.load_env`. When `null`, liter-llm's
     * own default behavior applies.
     */
    val loadEnv: Boolean? = null,
    /**
     * Extra HTTP headers sent with every request to the provider.
     *
     * Mirrors liter-llm's `ClientConfigBuilder.header`, for gateways or providers
     * that require custom auth/routing headers.
     */
    val headers: Map<String, String>? = null,
    /**
     * Custom provider configurations, in addition to liter-llm's built-in providers.
     *
     * Mirrors liter-llm's `LlmConfig.providers`, for OpenAI-compatible gateways
     * and self-hosted model servers that are not in the built-in provider catalog.
     */
    val providers: List<LlmProviderConfig>? = null,
    /**
     * Response cache configuration.
     *
     * Mirrors liter-llm's `LlmConfig.cache`. Only takes effect when liter-llm's
     * `tower` feature is compiled in; otherwise the value is accepted but unused.
     *
     * Boxed for the same reason as `bedrock` (a4579589ac): `LlmConfig` is the payload
     * of `EmbeddingModelType.Llm` and `RerankerModelType.Llm`, whose other variants
     * are tens of bytes. Inlining this and the two sub-configs below pushed that
     * variant to 480 bytes and tripped `clippy.large_enum_variant` on the
     * `--features full` leg. ~keep
     */
    val cache: LlmCacheConfig? = null,
    /**
     * Budget enforcement configuration.
     *
     * Mirrors liter-llm's `LlmConfig.budget`. Only takes effect when liter-llm's
     * `tower` feature is compiled in; otherwise the value is accepted but unused.
     */
    val budget: LlmBudgetConfig? = null,
    /**
     * Per-model rate limiting configuration.
     *
     * Mirrors liter-llm's `LlmConfig.rate_limit`. Only takes effect when liter-llm's
     * `tower` feature is compiled in; otherwise the value is accepted but unused.
     */
    val rateLimit: LlmRateLimitConfig? = null,
    /**
     * Enable per-request cost tracking.
     *
     * Mirrors liter-llm's `LlmConfig.cost_tracking`. Only takes effect when
     * liter-llm's `tower` feature is compiled in; otherwise the value is accepted
     * but unused.
     */
    val costTracking: Boolean? = null,
    /**
     * Enable OpenTelemetry-compatible tracing spans.
     *
     * Mirrors liter-llm's `LlmConfig.tracing`. Only takes effect when liter-llm's
     * `tower` feature is compiled in; otherwise the value is accepted but unused.
     */
    val tracing: Boolean? = null,
    /**
     * Cooldown duration after transient errors, in seconds.
     *
     * Mirrors liter-llm's `LlmConfig.cooldown_secs`. Only takes effect when
     * liter-llm's `tower` feature is compiled in; otherwise the value is accepted
     * but unused.
     */
    val cooldownSecs: Long? = null,
    /**
     * Background health check interval, in seconds.
     *
     * Mirrors liter-llm's `LlmConfig.health_check_secs`. Only takes effect when
     * liter-llm's `tower` feature is compiled in; otherwise the value is accepted
     * but unused.
     */
    val healthCheckSecs: Long? = null,
    /**
     * AWS Bedrock settings (region, cross-region routing, explicit credentials).
     *
     * Only consulted for `bedrock/`-prefixed models. When `null` — or when an
     * individual field inside it is `null` — liter-llm falls back to the standard
     * AWS environment variables and the default credential chain.
     */
    val bedrock: BedrockConfig? = null,
)
