// Generated by alef. Do not edit by hand.
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * A custom provider configuration entry, in addition to liter-llm's built-in providers.
 *
 * Mirrors liter-llm's `LlmProviderConfig`.
 */
data class LlmProviderConfig(
    /** Provider name, used to key model prefix matching. */
    val name: String = "",
    /** Base URL for the provider's OpenAI-compatible API. */
    val baseUrl: String = "",
    /** Header name used to carry the API key (defaults to `Authorization` when unset). */
    val authHeader: String? = null,
    /** Model name prefixes routed to this provider (e.g. `["my-provider/"]`). */
    val modelPrefixes: List<String> = emptyList(),
)
