// Generated by alef. Do not edit by hand.
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Per-model rate limiting configuration.
 *
 * Mirrors liter-llm's `LlmRateLimitConfig`. Only takes effect when liter-llm's
 * `tower` feature is compiled in; otherwise the value round-trips through
 * configuration but is not enforced at request time.
 */
data class LlmRateLimitConfig(
    /** Requests per minute limit. */
    val rpm: Int? = null,
    /** Tokens per minute limit. */
    val tpm: Long? = null,
    /** Rate limit window, in seconds. */
    val windowSeconds: Long? = null,
)
