// Generated by alef. Do not edit by hand.
// alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Configuration for OCR element extraction.
 *
 * Controls how OCR elements are extracted and filtered.
 */
data class OcrElementConfig(
    /**
     * Whether to include OCR elements in the extraction result.
     *
     * When true, the `ocr_elements` field in `ExtractedDocument` will be populated.
     */
    val includeElements: Boolean = false,
    /**
     * Minimum hierarchical level to include.
     *
     * Elements below this level (e.g., words when min_level is Line) will be excluded.
     */
    val minLevel: OcrElementLevel = OcrElementLevel.LINE,
    /**
     * Minimum recognition confidence threshold (0.0-1.0).
     *
     * Elements with confidence below this threshold will be filtered out.
     */
    val minConfidence: Double = 0.0,
    /**
     * Whether to build hierarchical relationships between elements.
     *
     * When true, `parent_id` fields will be populated based on spatial containment.
     * Only meaningful for Tesseract output.
     */
    val buildHierarchy: Boolean = false,
)
