// Generated by alef. Do not edit by hand.
// alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48

package io.xberg

object PostProcessorBridge {
    private val registered = mutableMapOf<String, IPostProcessor>()

    fun register(impl: IPostProcessor): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterPostProcessor(PostProcessorJniDispatcher(impl))
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterPostProcessor(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearPostProcessors()
    }

    fun getAll(): Map<String, IPostProcessor> = registered.toMap()
}
