// Generated by alef. Do not edit by hand.
// alef:hash:56c54dd10c8402cdf1e45cb09a8447a5d449d40b92f8fdea06329900bfdd9972

package io.xberg

object RendererBridge {
    private val registered = mutableMapOf<String, IRenderer>()

    fun register(impl: IRenderer): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterRenderer(RendererJniDispatcher(impl))
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterRenderer(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearRenderers()
    }

    fun getAll(): Map<String, IRenderer> = registered.toMap()
}
