// Generated by alef. Do not edit by hand.
// alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1

package io.xberg

object TokenizerBackendBridge {
    private val registered = mutableMapOf<String, ITokenizerBackend>()

    fun register(impl: ITokenizerBackend): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterTokenizerBackend(TokenizerBackendJniDispatcher(impl))
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterTokenizerBackend(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearTokenizerBackends()
    }

    fun getAll(): Map<String, ITokenizerBackend> = registered.toMap()
}
