// Generated by alef. Do not edit by hand.
// alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48

package io.xberg

object ValidatorBridge {
    private val registered = mutableMapOf<String, IValidator>()

    fun register(impl: IValidator): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterValidator(ValidatorJniDispatcher(impl))
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterValidator(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearValidators()
    }

    fun getAll(): Map<String, IValidator> = registered.toMap()
}
