// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Where the heading-path breadcrumb is written when
 * ChunkingConfig.prepend_heading_context(super.super.processing.ChunkingConfig.prepend_heading_context)
 * is enabled for a {@code Markdown}-chunked document.
 *
 * Prepending the breadcrumb into a chunk's {@code content} (the default, {@code
 * Content}) helps dense/embedding retrieval: each chunk becomes a
 * self-contained passage that carries its own structural context. It actively
 * harms lexical retrieval (BM25/TF-IDF), though — every chunk under the same
 * section repeats the same heading tokens, so a heading word's document
 * frequency approaches the number of chunks in that section and its IDF
 * collapses toward zero, drowning out real match signal.
 *
 * {@code Metadata} keeps {@code content} free of the breadcrumb and relies
 * solely on ChunkMetadata.heading_path(crate.types.ChunkMetadata.heading_path)
 * (already populated for every chunk under a heading by
 * chunk_for_rag(crate.chunking.chunk_for_rag)), which downstream lexical/hybrid
 * pipelines can use to exclude or down-weight heading tokens directly — instead
 * of the fragile pattern of string-stripping a breadcrumb prefix back out of
 * {@code content}.
 *
 * There is deliberately no {@code Both} variant. {@code heading_path} is
 * populated for every chunk under a heading regardless of this setting, so
 * "both" is precisely what
 * {@code Content} already does — a third variant would be a synonym, and one
 * that every binding in 15 languages would have to carry and every caller would
 * have to guess the meaning of.
 */
@SuppressWarnings("PMD")
public enum BreadcrumbTarget {
  /**
   * Prepend the heading breadcrumb into chunk {@code content}, and keep {@code
   * heading_path} populated (default; preserves the behaviour that existed
   * before this option was introduced).
   */
  Content("content"),
  /**
   * Leave {@code content} untouched; rely on {@code ChunkMetadata.heading_path}
   * only.
   */
  Metadata("metadata");

  /** The string value. */
  private final String value;

  BreadcrumbTarget(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static BreadcrumbTarget fromValue(final String value) {
    for (BreadcrumbTarget e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown BreadcrumbTarget value: " +
                                       value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
