// DO NOT EDIT - auto-generated by alef
// alef:hash:fa515707dbd85dfa280fe1f41a14dc0bad9251e7ef06d80bad45f43acd082c07
package io.xberg;

/**
 * A cache read or write operation failed.
 */
public class CacheException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new CacheException with the given message. */
  public CacheException(final String message) {
    super(message);
  }

  /** Creates a new CacheException with the given message and cause. */
  public CacheException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
