// DO NOT EDIT - auto-generated by alef
// alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
package io.xberg;

/**
 * The extraction was cancelled via a `CancellationToken`.
 */
public class CancelledException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new CancelledException with the given message. */
    public CancelledException(final String message) {
        super(message);
    }

    /** Creates a new CancelledException with the given message and cause. */
    public CancelledException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
