// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:174d6af235fa52e1e75c3385aa2847c36ed419d1afd59cc4ee9d07e25bc619ca
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

/**
 * Chunk-classification enrichment knob: how to multi-label individual chunks.
 *
 * Operates on {@code ExtractedDocument.chunks} in place — the caller must have
 * already produced chunks (e.g. via {@code ExtractionConfig.chunking}) for this
 * stage to have any effect; a document with no chunks is a no-op.
 */
public record ChunkClassificationEnrichmentConfig(ChunkClassificationConfig config) {
}
