// DO NOT EDIT - auto-generated by alef
// alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
package io.xberg;

/**
 * Invalid configuration value.
 */
public class ConfigErrorException extends HeuristicsErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ConfigErrorException with the given message. */
  public ConfigErrorException(final String message) { super(message); }

  /** Creates a new ConfigErrorException with the given message and cause. */
  public ConfigErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
