// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e198b852a723bf711781f8ea76fe7631d286ad23cf044681569349e65fcea808
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

/** Exception thrown when type conversion fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class ConversionErrorException extends XbergRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ConversionErrorException. */
  public ConversionErrorException(final String message) {
    super(2, message);
  }

  /** Creates a new ConversionErrorException with a cause. */
  public ConversionErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
