// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

/** Exception thrown when type conversion fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class ConversionErrorException extends XbergRsException {
    private static final long serialVersionUID = 1L;

    /** Creates a new ConversionErrorException. */
    public ConversionErrorException(final String message) {
        super(2, message);
    }

    /** Creates a new ConversionErrorException with a cause. */
    public ConversionErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
