// DO NOT EDIT - auto-generated by alef
// alef:hash:8d1f0daf96f86ea382e83e9fcbe60f2738eddacc8d6cdc55a747df6942f9f353
package io.xberg;

/**
 * The file validates but cannot be deserialized into [`Preset`].
 */
public class DeserializeException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DeserializeException with the given message. */
  public DeserializeException(final String message) {
    super(message);
  }

  /** Creates a new DeserializeException with the given message and cause. */
  public DeserializeException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
