// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import java.util.List;

/**
 * Changes to embedded archive children between two results.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EmbeddedChanges.Builder.class)
public record
EmbeddedChanges(@JsonProperty("added") List<ArchiveEntry> added,
                @JsonProperty("removed") List<ArchiveEntry> removed,
                @JsonProperty("changed") List<EmbeddedDiff> changed) {
  /** Creates a new Builder for constructing instances of this record. */
  public static Builder builder() { return new Builder(); }

  // CPD-OFF
  /** Jackson builder for EmbeddedChanges deserialization. */
  @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
  @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
  public static final class Builder {

    private List<ArchiveEntry> added = List.of();
    private List<ArchiveEntry> removed = List.of();
    private List<EmbeddedDiff> changed = List.of();

    /** Sets the added field. */
    @JsonProperty("added")
    public Builder withAdded(final List<ArchiveEntry> value) {
      this.added = value;
      return this;
    }

    /** Sets the removed field. */
    @JsonProperty("removed")
    public Builder withRemoved(final List<ArchiveEntry> value) {
      this.removed = value;
      return this;
    }

    /** Sets the changed field. */
    @JsonProperty("changed")
    public Builder withChanged(final List<EmbeddedDiff> value) {
      this.changed = value;
      return this;
    }

    /**
     * Constructs a EmbeddedChanges instance from the builder's current state.
     */
    public EmbeddedChanges build() {
      return new EmbeddedChanges(added, removed, changed);
    }
  }
  // CPD-ON
}
