// DO NOT EDIT - auto-generated by alef
// alef:hash:244c9f92bb9d2020c497f8e25b87b80d3f44814cc86bd334680046c31da2c4a2
package io.xberg;

/**
 * The embedding model or embedding pipeline returned an error.
 */
public class EmbeddingException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new EmbeddingException with the given message. */
  public EmbeddingException(final String message) {
    super(message);
  }

  /** Creates a new EmbeddingException with the given message and cause. */
  public EmbeddingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
