// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8e1c516b84bd6899c79a6ec23396311ca2665f830fb7ece4dd4a895d40f00c57
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Configuration for markdown footnote and citation parsing.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FootnoteConfig.Builder.class)
public record FootnoteConfig(@Nullable @JsonProperty("parse_citations") Boolean parseCitations) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }
    public FootnoteConfig{
        if (parseCitations == null) { parseCitations = true; }
    }

    // CPD-OFF
    /** Jackson builder for FootnoteConfig deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @JsonProperty("parse_citations")
        @Nullable private Boolean parseCitations;

        /** Sets the parseCitations field. */
        @JsonProperty("parse_citations")
        public Builder withParseCitations(final @Nullable Boolean value) {
            this.parseCitations = value;
            return this;
        }

        /** Constructs a FootnoteConfig instance from the builder's current state. */
        public FootnoteConfig build() {
            return new FootnoteConfig(
                parseCitations
            );
        }
    }
    // CPD-ON
}
