// DO NOT EDIT - auto-generated by alef
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
package io.xberg;

/**
 * Errors that can occur during heuristics analysis.
 */
public class HeuristicsErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new HeuristicsErrorException with the given message. */
  public HeuristicsErrorException(final String message) { super(message); }

  /**
   * Creates a new HeuristicsErrorException with the given message and cause.
   */
  public HeuristicsErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
