// DO NOT EDIT - auto-generated by alef
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
package io.xberg;

/**
 * The preset's declared `id` does not match its file-system location.
 */
public class IdMismatchException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new IdMismatchException with the given message. */
  public IdMismatchException(final String message) { super(message); }

  /** Creates a new IdMismatchException with the given message and cause. */
  public IdMismatchException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
