// DO NOT EDIT - auto-generated by alef
// alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
package io.xberg;

/**
 * The preset's declared `id` does not match its file-system location.
 */
public class IdMismatchException extends LoadErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new IdMismatchException with the given message. */
    public IdMismatchException(final String message) {
        super(message);
    }

    /** Creates a new IdMismatchException with the given message and cause. */
    public IdMismatchException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
