// DO NOT EDIT - auto-generated by alef
// alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
package io.xberg;

/**
 * The preset's declared `id` does not match its file-system location.
 */
public class IdMismatchException extends LoadErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new IdMismatchException with the given message. */
    public IdMismatchException(final String message) {
        super(message);
    }

    /** Creates a new IdMismatchException with the given message and cause. */
    public IdMismatchException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
