// DO NOT EDIT - auto-generated by alef
// alef:hash:15282a49a512037f41d759c5414263b43be290ef1e5765854a9730687f8a679c
package io.xberg;

/**
 * An image manipulation operation (resize, decode, DPI conversion) failed.
 */
public class ImageProcessingException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ImageProcessingException with the given message. */
  public ImageProcessingException(final String message) {
    super(message);
  }

  /** Creates a new ImageProcessingException with the given message and cause. */
  public ImageProcessingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
