// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2e8081cd134d8cf90d6662261a3e8d81aa039066405bdd919b3069f6fb9a61f8
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg;


/**
 * Bridge interface for the Renderer plugin system.
 *
 * Implementations are wrapped by RendererBridge and exposed to the native
 * runtime through Panama FFM upcall stubs.
 */
public interface IRenderer {

    /** Plugin name (used for registry keying). */
    String name();

    /** Plugin version. */
    String version();

    /** Initialize the plugin. */
    default void initialize() throws Exception {}

    /** Shut down the plugin. */
    default void shutdown() throws Exception {}

/** render_result. */    String render_result(ExtractedDocument result) throws Exception;
}
