// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c169c85ed2a78179628c454f2f26cc7f826ae26ff9c7115b9812eed9d24c2b7b
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg;


/**
 * Bridge interface for the Validator plugin system.
 *
 * Implementations are wrapped by ValidatorBridge and exposed to the native
 * runtime through Panama FFM upcall stubs.
 */
public interface IValidator {

    /** Plugin name (used for registry keying). */
    String name();

    /** Plugin version. */
    String version();

    /** Initialize the plugin. */
    default void initialize() throws Exception {}

    /** Shut down the plugin. */
    default void shutdown() throws Exception {}

/** validate. */    void validate(ExtractedDocument result, ExtractionConfig config) throws Exception;

/** should_validate. */    boolean should_validate(ExtractedDocument _result, ExtractionConfig _config) throws Exception;

/** priority. */    int priority() throws Exception;
}
