// DO NOT EDIT - auto-generated by alef
// alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
package io.xberg;

/**
 * Errors produced while loading or validating a preset file.
 */
public class LoadErrorException extends Exception {
    private static final long serialVersionUID = 1L;
    /** Creates a new LoadErrorException with the given message. */
    public LoadErrorException(final String message) {
        super(message);
    }

    /** Creates a new LoadErrorException with the given message and cause. */
    public LoadErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
