// DO NOT EDIT - auto-generated by alef
// alef:hash:1c58f85410884fc711aaf33e8988f69e6d97714a84c511d0362b414fe1bb312a
package io.xberg;

/**
 * An internal `Mutex` or `RwLock` was found in a poisoned state.
 */
public class LockPoisonedException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new LockPoisonedException with the given message. */
  public LockPoisonedException(final String message) {
    super(message);
  }

  /** Creates a new LockPoisonedException with the given message and cause. */
  public LockPoisonedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
