// DO NOT EDIT - auto-generated by alef
// alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
package io.xberg;

/**
 * A catch-all for uncommon errors that do not fit another variant.
 */
public class OtherException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
