// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:865254ce216abab769f4cdfe2d6a79842dcce11c4e6cd05b0f3ad2b28e11f3e7
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Aggregate OCR legibility score for a page, reported by the backend that produced its text.
 *
 * This is distinct from OcrConfidence, which scores a single detected element (a word or
 * line) using detection/recognition confidence from the OCR engine itself. {@code PageOcrConfidence}
 * is a page-level summary computed after noise filtering, intended for triage of which pages
 * are worth a closer look, not for comparing OCR engines against each other.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PageOcrConfidence.Builder.class)
public record PageOcrConfidence(
    @Nullable @JsonProperty("score") Double score,
    @JsonProperty("word_count") int wordCount,
    @JsonProperty("backend") String backend
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for PageOcrConfidence deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @Nullable private Double score;
        @JsonProperty("word_count")
        private int wordCount;
        private String backend;

        /** Sets the score field. */
        @JsonProperty("score")
        public Builder withScore(final @Nullable double value) {
            this.score = value;
            return this;
        }

        /** Sets the wordCount field. */
        @JsonProperty("word_count")
        public Builder withWordCount(final int value) {
            this.wordCount = value;
            return this;
        }

        /** Sets the backend field. */
        @JsonProperty("backend")
        public Builder withBackend(final String value) {
            this.backend = value;
            return this;
        }

        /** Constructs a PageOcrConfidence instance from the builder's current state. */
        public PageOcrConfidence build() {
            return new PageOcrConfidence(
                score,
                wordCount,
                backend
            );
        }
    }
    // CPD-ON
}
