// DO NOT EDIT - auto-generated by alef
// alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
package io.xberg;

/**
 * The file is not valid JSON.
 */
public class ParseException extends LoadErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new ParseException with the given message. */
    public ParseException(final String message) {
        super(message);
    }

    /** Creates a new ParseException with the given message and cause. */
    public ParseException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
