// DO NOT EDIT - auto-generated by alef
// alef:hash:e53192a98d38113596f85f79ad713da1a8d68795626fa46f3628ed3ddb887036
package io.xberg;

/**
 * Document parsing failed (e.g. corrupt file, unsupported format feature).
 */
public class ParsingException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParsingException with the given message. */
  public ParsingException(final String message) {
    super(message);
  }

  /** Creates a new ParsingException with the given message and cause. */
  public ParsingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
