// DO NOT EDIT - auto-generated by alef
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
package io.xberg;

/**
 * PDF analysis step failed (only when `heuristics-pdf` feature is active).
 */
public class PdfAnalysisErrorException extends HeuristicsErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new PdfAnalysisErrorException with the given message. */
  public PdfAnalysisErrorException(final String message) { super(message); }

  /**
   * Creates a new PdfAnalysisErrorException with the given message and cause.
   */
  public PdfAnalysisErrorException(final String message,
                                   final Throwable cause) {
    super(message, cause);
  }
}
