// DO NOT EDIT - auto-generated by alef
// alef:hash:d094efdbcdd08a19dd8f83725522fcf1b2b3e8e5c403b7e865e1f225e22a632d
package io.xberg;

/**
 * PDF analysis step failed (only when `heuristics-pdf` feature is active).
 */
public class PdfAnalysisErrorException extends HeuristicsErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new PdfAnalysisErrorException with the given message. */
  public PdfAnalysisErrorException(final String message) {
    super(message);
  }

  /** Creates a new PdfAnalysisErrorException with the given message and cause. */
  public PdfAnalysisErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
