// DO NOT EDIT - auto-generated by alef
// alef:hash:338b69123e3f8dd3c7be942896d58c873d9795ea9f2f5a063cde66b0b808cc94
package io.xberg;

/**
 * A registered plugin returned an error during extraction.
 */
public class PluginException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new PluginException with the given message. */
  public PluginException(final String message) {
    super(message);
  }

  /** Creates a new PluginException with the given message and cause. */
  public PluginException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
