// DO NOT EDIT - auto-generated by alef
// alef:hash:c6bb54178aa6f906dcb870391e666a9e330e57aecc05b0da7b18da588a427787
package io.xberg;

/**
 * The reranker model or reranking pipeline returned an error.
 *
 * Since v5.0.0.
 */
public class RerankingException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new RerankingException with the given message. */
  public RerankingException(final String message) {
    super(message);
  }

  /** Creates a new RerankingException with the given message and cause. */
  public RerankingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
