// DO NOT EDIT - auto-generated by alef
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
package io.xberg;

/**
 * Errors produced while resolving a preset against caller overrides.
 */
public class ResolveErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new ResolveErrorException with the given message. */
  public ResolveErrorException(final String message) { super(message); }

  /** Creates a new ResolveErrorException with the given message and cause. */
  public ResolveErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
