// DO NOT EDIT - auto-generated by alef
// alef:hash:0cafec15da5cb6bb5341abdd31881dbee3bf453647602a2f53cee5663ffd8a05
package io.xberg;

/**
 * Errors produced while resolving a preset against caller overrides.
 */
public class ResolveErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new ResolveErrorException with the given message. */
  public ResolveErrorException(final String message) {
    super(message);
  }

  /** Creates a new ResolveErrorException with the given message and cause. */
  public ResolveErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
