// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import java.util.List;
import org.jspecify.annotations.Nullable;

/**
 * The content changes that make up a single revision.
 *
 * For insertions and deletions the {@code content} field carries the
 * added/removed lines as {@code DiffLine.Added} / {@code DiffLine.Removed}
 * entries. For format changes, {@code property_changes} carries normalized
 * before/after formatting values when the source document exposes them.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = RevisionDelta.Builder.class)
public record
RevisionDelta(@JsonProperty("content") List<DiffLine> content,
              @JsonProperty("table_changes") List<CellChange> tableChanges,
              @Nullable @JsonProperty("property_changes")
              List<PropertyChange> propertyChanges) {
  /** Creates a new Builder for constructing instances of this record. */
  public static Builder builder() { return new Builder(); }

  // CPD-OFF
  /** Jackson builder for RevisionDelta deserialization. */
  @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
  @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
  public static final class Builder {

    private List<DiffLine> content = List.of();
    @JsonProperty("table_changes")
    private List<CellChange> tableChanges = List.of();
    @JsonProperty("property_changes")
    @Nullable
    private List<PropertyChange> propertyChanges;

    /** Sets the content field. */
    @JsonProperty("content")
    public Builder withContent(final List<DiffLine> value) {
      this.content = value;
      return this;
    }

    /** Sets the tableChanges field. */
    @JsonProperty("table_changes")
    public Builder withTableChanges(final List<CellChange> value) {
      this.tableChanges = value;
      return this;
    }

    /** Sets the propertyChanges field. */
    @JsonProperty("property_changes")
    public Builder withPropertyChanges(final
                                       @Nullable List<PropertyChange> value) {
      this.propertyChanges = value;
      return this;
    }

    /** Constructs a RevisionDelta instance from the builder's current state. */
    public RevisionDelta build() {
      return new RevisionDelta(content, tableChanges, propertyChanges);
    }
  }
  // CPD-ON
}
