// DO NOT EDIT - auto-generated by alef
// alef:hash:3d413677c727b7caa4fc20d8adc6a159b800c0e791fd81093f4e53ff83ac5fc3
package io.xberg;

/**
 * The file parses as JSON but does not validate against the meta-schema.
 */
public class SchemaValidationException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SchemaValidationException with the given message. */
  public SchemaValidationException(final String message) {
    super(message);
  }

  /** Creates a new SchemaValidationException with the given message and cause. */
  public SchemaValidationException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
