// DO NOT EDIT - auto-generated by alef
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
package io.xberg;

/**
 * The file parses as JSON but does not validate against the meta-schema.
 */
public class SchemaValidationException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SchemaValidationException with the given message. */
  public SchemaValidationException(final String message) { super(message); }

  /**
   * Creates a new SchemaValidationException with the given message and cause.
   */
  public SchemaValidationException(final String message,
                                   final Throwable cause) {
    super(message, cause);
  }
}
