// DO NOT EDIT - auto-generated by alef
// alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
package io.xberg;

/**
 * The file parses as JSON but does not validate against the meta-schema.
 */
public class SchemaValidationException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SchemaValidationException with the given message. */
  public SchemaValidationException(final String message) { super(message); }

  /**
   * Creates a new SchemaValidationException with the given message and cause.
   */
  public SchemaValidationException(final String message,
                                   final Throwable cause) {
    super(message, cause);
  }
}
