// DO NOT EDIT - auto-generated by alef
// alef:hash:35752773a21fda9dd9c4126d961bd735f72ce5b9d035a55c12081fd151628a28
package io.xberg;

/**
 * A custom schema override was supplied but is not a JSON object.
 */
public class SchemaNotObjectException extends ResolveErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SchemaNotObjectException with the given message. */
  public SchemaNotObjectException(final String message) {
    super(message);
  }

  /** Creates a new SchemaNotObjectException with the given message and cause. */
  public SchemaNotObjectException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
