// DO NOT EDIT - auto-generated by alef
// alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
package io.xberg;

/**
 * A security policy was violated (e.g. zip bomb, oversized archive).
 */
public class SecurityException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new SecurityException with the given message. */
    public SecurityException(final String message) {
        super(message);
    }

    /** Creates a new SecurityException with the given message and cause. */
    public SecurityException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
