// DO NOT EDIT - auto-generated by alef
// alef:hash:1562b1a2d3a2cb1bbfa8c9bafc682054f2f8463ddeb109086260a2b990316faf
package io.xberg;

/**
 * JSON or MessagePack serialization/deserialization failed.
 */
public class SerializationException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SerializationException with the given message. */
  public SerializationException(final String message) {
    super(message);
  }

  /** Creates a new SerializationException with the given message and cause. */
  public SerializationException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
