// DO NOT EDIT - auto-generated by alef
// alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
package io.xberg;

/**
 * The extraction operation exceeded the configured time limit.
 */
public class TimeoutException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new TimeoutException with the given message. */
  public TimeoutException(final String message) { super(message); }

  /** Creates a new TimeoutException with the given message and cause. */
  public TimeoutException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
