// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:12c3548d1a46b14e3c49b6484b72d86aa733062ff3f1619655d1c5637e69d529
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg;

/**
 * Path A Bridge implementation for ITokenizerBackend.
 *
 * Wraps a user-supplied implementation and delegates all method calls.
 * This adapter conforms to the hand-authored sealed interface.
 */
public final class TokenizerBackendAdapter implements ITokenizerBackend {
    private final ITokenizerBackend impl;

    public TokenizerBackendAdapter(ITokenizerBackend impl) {
        this.impl = impl;
    }

    @Override
    public String name() {
        return impl.name();
    }

    @Override
    public String version() {
        return impl.version();
    }

    @Override
    public void initialize() throws Exception {
        impl.initialize();
    }

    @Override
    public void shutdown() throws Exception {
        impl.shutdown();
    }

    @Override
    public long count_tokens(String text) throws Exception {
        return impl.count_tokens(text);
    }


}
