// DO NOT EDIT - auto-generated by alef
// alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
package io.xberg;

/**
 * The document's MIME type is not supported by any registered extractor.
 */
public class UnsupportedFormatException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new UnsupportedFormatException with the given message. */
    public UnsupportedFormatException(final String message) {
        super(message);
    }

    /** Creates a new UnsupportedFormatException with the given message and cause. */
    public UnsupportedFormatException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
