// DO NOT EDIT - auto-generated by alef
// alef:hash:e2b369a02658e3180e8cb5238c7a0bca9c9d97b86fd9205d6d35948f6844f777
package io.xberg;

/**
 * Invalid configuration or input parameters were supplied.
 */
public class ValidationException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ValidationException with the given message. */
  public ValidationException(final String message) {
    super(message);
  }

  /** Creates a new ValidationException with the given message and cause. */
  public ValidationException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
