// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

/** Exception thrown by XbergRs. */
public class XbergRsException extends Exception {
    private static final long serialVersionUID = 1L;
    /** The error code. */
    private final int code;

    /** Creates a new XbergRsException. */
    public XbergRsException(final int code, final String message) {
        super(message);
        this.code = code;
    }

    /** Creates a new XbergRsException with a cause. */
    public XbergRsException(final String message, final Throwable cause) {
        super(message, cause);
        this.code = -1;
    }

    /** Returns the error code. */
    public int getCode() {
        return code;
    }
}
