# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'registry' do
  it 'list_embedding_backends: List embedding backends' do
    result = Xberg.list_embedding_backends()

    expect(result).not_to be_nil
  end

  it 'list_ocr_backends: List OCR backends' do
    result = Xberg.list_ocr_backends()

    expect(result).not_to be_nil
  end

  it 'list_post_processors: List post-processors' do
    result = Xberg.list_post_processors()

    expect(result).not_to be_nil
  end

  it 'list_renderers: List renderers' do
    result = Xberg.list_renderers()

    expect(result).not_to be_nil
  end

  it 'list_validators: List validators' do
    result = Xberg.list_validators()

    expect(result).not_to be_nil
  end
end
