# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c42b3ed17053806bdcf42dea768a2aecba67c8ec1370751ea7323b02483cbce1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'reranker_backend_management' do
  it 'clear_reranker_backends: Clear all reranker backends and verify list is empty' do
    Xberg.clear_reranker_backends()

  end

  it 'list_reranker_backends: List all registered reranker backends' do
    result = Xberg.list_reranker_backends()

    expect(result).not_to be_nil
  end
end
