# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5b65fe8ac640bf4cdf1e1a281c4b41b6d0d521d562ffcfc7007265ad142fb846
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'reranker_backend_management' do
  it 'clear_reranker_backends: Clear all reranker backends and verify list is empty' do
    Xberg.clear_reranker_backends()

  end

  it 'list_reranker_backends: List all registered reranker backends' do
    result = Xberg.list_reranker_backends()

    expect(result).not_to be_nil
  end
end
