# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5b65fe8ac640bf4cdf1e1a281c4b41b6d0d521d562ffcfc7007265ad142fb846
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'tokenizer_backend_management' do
  it 'tokenizer_backends_clear: Clear all tokenizer backends and verify list is empty' do
    Xberg.clear_tokenizer_backends()

  end

  it 'tokenizer_backends_list: List all registered tokenizer backends' do
    result = Xberg.list_tokenizer_backends()

    expect(result).not_to be_nil
  end
end
