# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5ecb8b848ec71073c48cd789bb042be0492601020f639d4f900437051e467182
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module Xberg
  ## The version string for this package.
  VERSION = "1.0.14"
end
