<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a9d5fe26f0500910dd7bcc2206c22e9579b6db06e90a4baf7d73a357c31f491b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Xberg;

/**
 * Per-category running counter for `RedactionStrategy.TokenReplace`.
 */
final class TokenCounter
{
    /**
     * Create a fresh counter with no previous state.
     */
    public static function new(): TokenCounter
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
