// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:664ff8853e4f337cc9a5eea9291b7e00717a1cfcacf11bac75c7c1710ffbced9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: post_processor_management
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg/packages/go"
)

func Test_PostProcessorsClear(t *testing.T) {
	// Clear all post-processors and verify list is empty
	_ = xberg.ClearPostProcessors()
}

func Test_PostProcessorsList(t *testing.T) {
	// List all registered post-processors
	_, err := xberg.ListPostProcessors()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
