// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f21c73d7316bf5bb9a542d4cfd69e8c313008c660a0167cafab5e4cd71457a48
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: validator_management
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg/packages/go"
)

func Test_ValidatorsClear(t *testing.T) {
	// Clear all validators and verify list is empty
	_ = xberg.ClearValidators()
}

func Test_ValidatorsList(t *testing.T) {
	// List all registered validators
	_, err := xberg.ListValidators()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
